/*
 *    MCreator note: This file will be REGENERATED on each build.
 */
package net.mcreator.buildingmod.init;

import net.neoforged.neoforge.registries.DeferredRegister;
import net.neoforged.neoforge.registries.DeferredItem;
import net.neoforged.neoforge.registries.DeferredHolder;
import net.neoforged.neoforge.capabilities.RegisterCapabilitiesEvent;
import net.neoforged.neoforge.capabilities.Capabilities;
import net.neoforged.fml.common.EventBusSubscriber;
import net.neoforged.bus.api.SubscribeEvent;

import net.minecraft.world.level.block.Block;
import net.minecraft.world.item.Item;
import net.minecraft.world.item.DoubleHighBlockItem;
import net.minecraft.world.item.BlockItem;

import net.mcreator.buildingmod.item.inventory.HelperPaperInventoryCapability;
import net.mcreator.buildingmod.item.*;
import net.mcreator.buildingmod.DavebuildingmodMod;

@EventBusSubscriber
public class DavebuildingmodModItems {
	public static final DeferredRegister.Items REGISTRY = DeferredRegister.createItems(DavebuildingmodMod.MODID);
	public static final DeferredItem<Item> LIGHTON;
	public static final DeferredItem<Item> LIGHTOFF;
	public static final DeferredItem<Item> ALARM_LIGHTOFF;
	public static final DeferredItem<Item> ALARM_LIGHTON;
	public static final DeferredItem<Item> GREEN_LIGHT_ON;
	public static final DeferredItem<Item> GREEN_LIGHT_OFF;
	public static final DeferredItem<Item> BLUE_LIGHT_OFF;
	public static final DeferredItem<Item> BLUE_LIGHT_ON;
	public static final DeferredItem<Item> SOUND_GENERATOR;
	public static final DeferredItem<Item> PARTICLE_GENERATOR;
	public static final DeferredItem<Item> STRIPEDBLOCK;
	public static final DeferredItem<Item> ALARM_BLOCK;
	public static final DeferredItem<Item> RADIATION_BLOCK;
	public static final DeferredItem<Item> BIOHAZARD_BLOCK;
	public static final DeferredItem<Item> DEATH_BLOCK;
	public static final DeferredItem<Item> ELECTRICITY_BLOCK;
	public static final DeferredItem<Item> CROSS_BLOCK;
	public static final DeferredItem<Item> BASIC_CIRCUIT;
	public static final DeferredItem<Item> ADVANCED_CIRCUIT;
	public static final DeferredItem<Item> STRIPPEDBLOCK_HORIZONTAL;
	public static final DeferredItem<Item> STEEL_INGOT;
	public static final DeferredItem<Item> STEEL_PLATING;
	public static final DeferredItem<Item> STEEL_TILES;
	public static final DeferredItem<Item> STEEL_PILLAR;
	public static final DeferredItem<Item> STEEL_SEEMLESS;
	public static final DeferredItem<Item> STEEL_DOOR;
	public static final DeferredItem<Item> STEEL_TRAPDOOR;
	public static final DeferredItem<Item> STEEL_STAIRS;
	public static final DeferredItem<Item> STEEL_SLAB;
	public static final DeferredItem<Item> STEEL_WALL;
	public static final DeferredItem<Item> VENT_STRAIGHT;
	public static final DeferredItem<Item> VENT_L;
	public static final DeferredItem<Item> VENT_L_UP;
	public static final DeferredItem<Item> PC_SETUP;
	public static final DeferredItem<Item> COMPUTER_TERMINAL;
	public static final DeferredItem<Item> SERVER_RACK;
	public static final DeferredItem<Item> EXIT_SIGN;
	public static final DeferredItem<Item> BLACK_QUILTED_WOOL;
	public static final DeferredItem<Item> SOFT_AIR;
	public static final DeferredItem<Item> LABORATORY_BLOCK;
	public static final DeferredItem<Item> LABORATORY_VENT;
	public static final DeferredItem<Item> LABORATORY_PANEL;
	public static final DeferredItem<Item> LABORATORY_STRIPE;
	public static final DeferredItem<Item> COPPER_COIL;
	public static final DeferredItem<Item> ISOLINEAR_FRONT_BLUE;
	public static final DeferredItem<Item> ISOLINEAR_MIDDLE_BLUE;
	public static final DeferredItem<Item> ISOLINEAR_BACK_BLUE;
	public static final DeferredItem<Item> CUT_LABORATORY_BLOCK;
	public static final DeferredItem<Item> VOCALS_GENERATOR;
	public static final DeferredItem<Item> VOCAL_EMPTY;
	public static final DeferredItem<Item> REINFORCED_GLASS;
	public static final DeferredItem<Item> LABORATORY_ROMAN_1;
	public static final DeferredItem<Item> LABORATORY_ROMAN_5;
	public static final DeferredItem<Item> LABORATORY_ROMAN_10;
	public static final DeferredItem<Item> ISOLINEAR_BACK_RED;
	public static final DeferredItem<Item> ISOLINEAR_BACK_GREEN;
	public static final DeferredItem<Item> ISOLINEAR_FRONT_GREEN;
	public static final DeferredItem<Item> ISOLINEAR_FRONT_RED;
	public static final DeferredItem<Item> ISOLINEAR_MIDDLE_RED;
	public static final DeferredItem<Item> ISOLINEAR_MIDDLE_GREEN;
	public static final DeferredItem<Item> ONEWAY_STONE;
	public static final DeferredItem<Item> VANTA_BLACK;
	public static final DeferredItem<Item> GREEN_SCREEN;
	public static final DeferredItem<Item> BLUE_SCREEN;
	public static final DeferredItem<Item> ONEWAY_LABORATORY_BLOCK;
	public static final DeferredItem<Item> RUBBER_DUCK;
	public static final DeferredItem<Item> FULL_LOG_PILE;
	public static final DeferredItem<Item> LOG_PILE_1_TOP;
	public static final DeferredItem<Item> LOG_PILE_2_BOTTOM;
	public static final DeferredItem<Item> LOG_PILE_2_TOP;
	public static final DeferredItem<Item> LOG_PILE_1_BOTTOM;
	public static final DeferredItem<Item> LOG_PALISADE;
	public static final DeferredItem<Item> BOOK_1;
	public static final DeferredItem<Item> BOOK_2;
	public static final DeferredItem<Item> SKELETON_1;
	public static final DeferredItem<Item> SKELETON_2;
	public static final DeferredItem<Item> SKELETON_3;
	public static final DeferredItem<Item> SKELETON_4;
	public static final DeferredItem<Item> YELLOW_ARROW_LEFT;
	public static final DeferredItem<Item> YELLOW_ARROW_RIGHT;
	public static final DeferredItem<Item> LABORATORY_LEFT_ARROW;
	public static final DeferredItem<Item> LABORATORY_RIGHT_ARROW;
	public static final DeferredItem<Item> LOG_PILE_CHAIR;
	public static final DeferredItem<Item> BLUE_QUILTED_WOOL;
	public static final DeferredItem<Item> BROWN_QUILTED_WOOL;
	public static final DeferredItem<Item> CYAN_QUILTED_WOOL;
	public static final DeferredItem<Item> GRAY_QUILTED_WOOL;
	public static final DeferredItem<Item> GREEN_QUILTED_WOOL;
	public static final DeferredItem<Item> LIGHT_BLUE_QUILTED_WOOL;
	public static final DeferredItem<Item> LIGHT_GRAY_QUILTED_WOOL;
	public static final DeferredItem<Item> LIME_QUILTED_WOOL;
	public static final DeferredItem<Item> MAGENTA_QUILTED_WOOL;
	public static final DeferredItem<Item> ORANGE_QUILTED_WOOL;
	public static final DeferredItem<Item> PINK_QUILTED_WOOL;
	public static final DeferredItem<Item> PURPLE_QUILTED_WOOL;
	public static final DeferredItem<Item> RED_QUILTED_WOOL;
	public static final DeferredItem<Item> WHITE_QUILTED_WOOL;
	public static final DeferredItem<Item> YELLOW_QUILTED_WOOL;
	public static final DeferredItem<Item> BLACK_CHAIR;
	public static final DeferredItem<Item> BLUE_CHAIR;
	public static final DeferredItem<Item> BROWN_CHAIR;
	public static final DeferredItem<Item> CYAN_CHAIR;
	public static final DeferredItem<Item> GRAY_CHAIR;
	public static final DeferredItem<Item> GREEN_CHAIR;
	public static final DeferredItem<Item> LIGHT_BLUE_CHAIR;
	public static final DeferredItem<Item> LIGHT_GRAY_CHAIR;
	public static final DeferredItem<Item> LIME_CHAIR;
	public static final DeferredItem<Item> MAGENTA_CHAIR;
	public static final DeferredItem<Item> ORANGE_CHAIR;
	public static final DeferredItem<Item> PINK_CHAIR;
	public static final DeferredItem<Item> PURPLE_CHAIR;
	public static final DeferredItem<Item> RED_CHAIR;
	public static final DeferredItem<Item> WHITE_CHAIR;
	public static final DeferredItem<Item> YELLOW_CHAIR;
	public static final DeferredItem<Item> HALF_LUMBER_DIAGONAL_LEFT;
	public static final DeferredItem<Item> HALF_LUMBER_DIAGONAL_RIGHT;
	public static final DeferredItem<Item> HALF_LUMBER_VERTICAL;
	public static final DeferredItem<Item> HALF_LUMBER_HORIZONTAL;
	public static final DeferredItem<Item> HALF_LUMBER_BORDER;
	public static final DeferredItem<Item> HALF_LUMBER_BRICK_BORDER;
	public static final DeferredItem<Item> HALF_LUMBER_BRICK_DIAGONAL_LEFT;
	public static final DeferredItem<Item> HALF_LUMBER_BRICK_DIAGONAL_RIGHT;
	public static final DeferredItem<Item> HALF_LUMBER_BRICK_HORIZONTAL;
	public static final DeferredItem<Item> HALF_LUMBER_BRICK_VERTICAL;
	public static final DeferredItem<Item> ROCKY_DIRT;
	public static final DeferredItem<Item> STEEL_FRAME;
	public static final DeferredItem<Item> POLISHED_STEEL_PLATING;
	public static final DeferredItem<Item> TUNGSTEN_CARBITE;
	public static final DeferredItem<Item> STEEL_COLOUMN;
	public static final DeferredItem<Item> TRACK_END;
	public static final DeferredItem<Item> CREATE_BOILER;
	public static final DeferredItem<Item> BLACK_BOILER;
	public static final DeferredItem<Item> BLACK_STEEL_TANK;
	public static final DeferredItem<Item> BLACK_STEEL_PLATING;
	public static final DeferredItem<Item> BLACK_STEEL_STAIRS;
	public static final DeferredItem<Item> BLACK_STEEL_SLAB;
	public static final DeferredItem<Item> BLACK_STEEL_TRAPDOOR;
	public static final DeferredItem<Item> BLACK_STEEL_WALL;
	public static final DeferredItem<Item> STEEL_GIRDER;
	public static final DeferredItem<Item> RED_STEEL_PLATING;
	public static final DeferredItem<Item> RED_STEEL_STAIRS;
	public static final DeferredItem<Item> RED_STEEL_SLAB;
	public static final DeferredItem<Item> RED_STEEL_TRAPDOOR;
	public static final DeferredItem<Item> RED_STEEL_WALL;
	public static final DeferredItem<Item> BLACK_GUILDER_STEEL_TANK;
	public static final DeferredItem<Item> BLACK_GUILDED_BOILER;
	public static final DeferredItem<Item> RED_GUILDED_STEEL_TANK;
	public static final DeferredItem<Item> RED_STEEL_TANK;
	public static final DeferredItem<Item> RED_BOILER;
	public static final DeferredItem<Item> RED_GUILDED_BOILER;
	public static final DeferredItem<Item> GREEN_GILDED_STEEL_TANK;
	public static final DeferredItem<Item> GREEN_STEEL_PLATING;
	public static final DeferredItem<Item> GREEN_STEEL_SLAB;
	public static final DeferredItem<Item> GREEN_STEEL_STAIRS;
	public static final DeferredItem<Item> GREEN_STEEL_TANK;
	public static final DeferredItem<Item> GREEN_STEEL_TRAPDOOR;
	public static final DeferredItem<Item> GREEN_STEEL_WALL;
	public static final DeferredItem<Item> GREEN_BOILER;
	public static final DeferredItem<Item> GREEN_GILDED_BOILER;
	public static final DeferredItem<Item> BROWN_GILDED_STEEL_TANK;
	public static final DeferredItem<Item> BROWN_STEEL_PLATING;
	public static final DeferredItem<Item> BROWN_STEEL_SLAB;
	public static final DeferredItem<Item> BROWN_STEEL_STAIRS;
	public static final DeferredItem<Item> BROWN_STEEL_TANK;
	public static final DeferredItem<Item> BROWN_STEEL_TRAPDOOR;
	public static final DeferredItem<Item> BROWN_STEEL_WALL;
	public static final DeferredItem<Item> BROWN_BOILER;
	public static final DeferredItem<Item> BROWN_GILDED_BOILER;
	public static final DeferredItem<Item> BLUE_GILDED_STEEL_TANK;
	public static final DeferredItem<Item> BLUE_STEEL_PLATING;
	public static final DeferredItem<Item> BLUE_STEEL_SLAB;
	public static final DeferredItem<Item> BLUE_STEEL_STAIRS;
	public static final DeferredItem<Item> BLUE_STEEL_TANK;
	public static final DeferredItem<Item> BLUE_STEEL_TRAPDOOR;
	public static final DeferredItem<Item> BLUE_STEEL_WALL;
	public static final DeferredItem<Item> BLUE_BOILER;
	public static final DeferredItem<Item> BLUE_GILDED_BOILER;
	public static final DeferredItem<Item> PURPLE_GILDED_STEEL_TANK;
	public static final DeferredItem<Item> PURPLE_STEEL_PLATING;
	public static final DeferredItem<Item> PURPLE_STEEL_SLAB;
	public static final DeferredItem<Item> PURPLE_STEEL_STAIRS;
	public static final DeferredItem<Item> PURPLE_STEEL_TANK;
	public static final DeferredItem<Item> PURPLE_STEEL_TRAPDOOR;
	public static final DeferredItem<Item> PURPLE_STEEL_WALL;
	public static final DeferredItem<Item> CYAN_GILDED_STEEL_TANK;
	public static final DeferredItem<Item> CYAN_STEEL_PLATING;
	public static final DeferredItem<Item> CYAN_STEEL_SLAB;
	public static final DeferredItem<Item> CYAN_STEEL_STAIRS;
	public static final DeferredItem<Item> CYAN_STEEL_TANK;
	public static final DeferredItem<Item> CYAN_STEEL_TRAPDOOR;
	public static final DeferredItem<Item> CYAN_STEEL_WALL;
	public static final DeferredItem<Item> PURPLE_BOILER;
	public static final DeferredItem<Item> PURPLE_GILDED_BOILER;
	public static final DeferredItem<Item> CYAN_BOILER;
	public static final DeferredItem<Item> CYAN_GILDED_BOILER;
	public static final DeferredItem<Item> LIGHT_GRAY_GILDED_STEEL_TANK;
	public static final DeferredItem<Item> LIGHT_GRAY_STEEL_PLATING;
	public static final DeferredItem<Item> LIGHT_GRAY_STEEL_SLAB;
	public static final DeferredItem<Item> LIGHT_GRAY_STEEL_STAIRS;
	public static final DeferredItem<Item> LIGHT_GRAY_STEEL_TANK;
	public static final DeferredItem<Item> LIGHT_GRAY_STEEL_TRAPDOOR;
	public static final DeferredItem<Item> LIGHT_GRAY_STEEL_WALL;
	public static final DeferredItem<Item> LIGHT_GRAY_BOILER;
	public static final DeferredItem<Item> LIGHT_GRAY_GILDED_BOILER;
	public static final DeferredItem<Item> GRAY_GILDED_STEEL_TANK;
	public static final DeferredItem<Item> GRAY_STEEL_PLATING;
	public static final DeferredItem<Item> GRAY_STEEL_SLAB;
	public static final DeferredItem<Item> GRAY_STEEL_STAIRS;
	public static final DeferredItem<Item> GRAY_STEEL_TANK;
	public static final DeferredItem<Item> GRAY_STEEL_TRAPDOOR;
	public static final DeferredItem<Item> GRAY_STEEL_WALL;
	public static final DeferredItem<Item> GRAY_BOILER;
	public static final DeferredItem<Item> GRAY_GILDED_BOILER;
	public static final DeferredItem<Item> PINK_GILDED_STEEL_TANK;
	public static final DeferredItem<Item> PINK_STEEL_PLATING;
	public static final DeferredItem<Item> PINK_STEEL_SLAB;
	public static final DeferredItem<Item> PINK_STEEL_STAIRS;
	public static final DeferredItem<Item> PINK_STEEL_TANK;
	public static final DeferredItem<Item> PINK_STEEL_TRAPDOOR;
	public static final DeferredItem<Item> PINK_STEEL_WALL;
	public static final DeferredItem<Item> LIME_GILDED_STEEL_TANK;
	public static final DeferredItem<Item> LIME_STEEL_PLATING;
	public static final DeferredItem<Item> LIME_STEEL_SLAB;
	public static final DeferredItem<Item> LIME_STEEL_STAIRS;
	public static final DeferredItem<Item> LIME_STEEL_TANK;
	public static final DeferredItem<Item> LIME_STEEL_TRAPDOOR;
	public static final DeferredItem<Item> LIME_STEEL_WALL;
	public static final DeferredItem<Item> PINK_BOILER;
	public static final DeferredItem<Item> PINK_GILDED_BOILER;
	public static final DeferredItem<Item> LIME_BOILER;
	public static final DeferredItem<Item> LIME_GILDED_BOILER;
	public static final DeferredItem<Item> YELLOW_GILDED_STEEL_TANK;
	public static final DeferredItem<Item> YELLOW_STEEL_PLATING;
	public static final DeferredItem<Item> YELLOW_STEEL_SLAB;
	public static final DeferredItem<Item> YELLOW_STEEL_STAIRS;
	public static final DeferredItem<Item> YELLOW_STEEL_TANK;
	public static final DeferredItem<Item> YELLOW_STEEL_TRAPDOOR;
	public static final DeferredItem<Item> YELLOW_STEEL_WALL;
	public static final DeferredItem<Item> YELLOW_BOILER;
	public static final DeferredItem<Item> YELLOW_GILDED_BOILER;
	public static final DeferredItem<Item> LIGHT_BLUE_GILDED_STEEL_TANK;
	public static final DeferredItem<Item> LIGHT_BLUE_STEEL_PLATING;
	public static final DeferredItem<Item> LIGHT_BLUE_STEEL_SLAB;
	public static final DeferredItem<Item> LIGHT_BLUE_STEEL_STAIRS;
	public static final DeferredItem<Item> LIGHT_BLUE_STEEL_TANK;
	public static final DeferredItem<Item> LIGHT_BLUE_STEEL_TRAPDOOR;
	public static final DeferredItem<Item> LIGHT_BLUE_STEEL_WALL;
	public static final DeferredItem<Item> MAGENTA_GILDED_STEEL_TANK;
	public static final DeferredItem<Item> MAGENTA_STEEL_PLATING;
	public static final DeferredItem<Item> MAGENTA_STEEL_SLAB;
	public static final DeferredItem<Item> MAGENTA_STEEL_STAIRS;
	public static final DeferredItem<Item> MAGENTA_STEEL_TANK;
	public static final DeferredItem<Item> MAGENTA_STEEL_TRAPDOOR;
	public static final DeferredItem<Item> MAGENTA_STEEL_WALL;
	public static final DeferredItem<Item> MAGENTA_BOILER;
	public static final DeferredItem<Item> MAGENTA_GILDED_BOILER;
	public static final DeferredItem<Item> ORANGE_GILDED_STEEL_TANK;
	public static final DeferredItem<Item> ORANGE_STEEL_PLATING;
	public static final DeferredItem<Item> ORANGE_STEEL_SLAB;
	public static final DeferredItem<Item> ORANGE_STEEL_STAIRS;
	public static final DeferredItem<Item> ORANGE_STEEL_TANK;
	public static final DeferredItem<Item> ORANGE_STEEL_TRAPDOOR;
	public static final DeferredItem<Item> ORANGE_STEEL_WALL;
	public static final DeferredItem<Item> ORANGE_BOILER;
	public static final DeferredItem<Item> ORANGE_GILDED_BOILER;
	public static final DeferredItem<Item> WHITE_GILDED_STEEL_TANK;
	public static final DeferredItem<Item> WHITE_STEEL_PLATING;
	public static final DeferredItem<Item> WHITE_STEEL_SLAB;
	public static final DeferredItem<Item> WHITE_STEEL_STAIRS;
	public static final DeferredItem<Item> WHITE_STEEL_TANK;
	public static final DeferredItem<Item> WHITE_STEEL_TRAPDOOR;
	public static final DeferredItem<Item> WHITE_STEEL_WALL;
	public static final DeferredItem<Item> WHITE_BOILER;
	public static final DeferredItem<Item> WHITE_GILDED_BOILER;
	public static final DeferredItem<Item> LIGHT_BLUE_BOILER;
	public static final DeferredItem<Item> LIGHT_BLUE_GILDED_BOILER;
	public static final DeferredItem<Item> STRIPEDBLOCK_MIDDLE;
	public static final DeferredItem<Item> GREEN_CIRCUIT_TNT_1;
	public static final DeferredItem<Item> GREEN_CIRCUIT_NUKE;
	public static final DeferredItem<Item> GREEN_CIRCUIT_XP_DING;
	public static final DeferredItem<Item> GREEN_CIRCUIT_LEVEL_UP;
	public static final DeferredItem<Item> GREEN_CIRCUIT_ITEM_BURN;
	public static final DeferredItem<Item> GREEN_CIRCUIT_FIRE_CHARGE;
	public static final DeferredItem<Item> GREEN_CIRCUIT_ELYTRA_FLY;
	public static final DeferredItem<Item> GREEN_CIRCUIT_BLAZE_HURT;
	public static final DeferredItem<Item> GREEN_CIRCUIT_BAT_TAKEOFF;
	public static final DeferredItem<Item> COMPUTER_TERMINAL_STEEL;
	public static final DeferredItem<Item> ROCKY_DIRT_SLAB;
	public static final DeferredItem<Item> DIRT_SLAB;
	public static final DeferredItem<Item> GRAVEL_SLAB;
	public static final DeferredItem<Item> BALLAST;
	public static final DeferredItem<Item> BALLAST_SLAB;
	public static final DeferredItem<Item> SKELETON_5;
	public static final DeferredItem<Item> SKELETON_6;
	public static final DeferredItem<Item> ARROW_UP_SIGN;
	public static final DeferredItem<Item> ARROW_RIGHT_SIGN;
	public static final DeferredItem<Item> ARROW_LEFT_SIGN;
	public static final DeferredItem<Item> ARROW_DOWN_SIGN;
	public static final DeferredItem<Item> ARROW_RETURN_SIGN;
	public static final DeferredItem<Item> NO_ENTRY_SIGN;
	public static final DeferredItem<Item> ALARM_SIGN;
	public static final DeferredItem<Item> ONEWAY_SIGN;
	public static final DeferredItem<Item> STEEL_BLOCK;
	public static final DeferredItem<Item> HELPER_PAPER;
	public static final DeferredItem<Item> STEEL_MESH_TRAPDOOR;
	public static final DeferredItem<Item> COPPER_BOILER;
	public static final DeferredItem<Item> BRASS_BOILER;
	public static final DeferredItem<Item> ZINC_BOILER;
	public static final DeferredItem<Item> GAUGE_OUTER;
	public static final DeferredItem<Item> GAUGE_INNER;
	public static final DeferredItem<Item> COW_CATCHER_WHITE;
	public static final DeferredItem<Item> COW_CATCHER_LIGHT_GRAY;
	public static final DeferredItem<Item> COW_CATCHER_GRAY;
	public static final DeferredItem<Item> COW_CATCHER_BLACK;
	public static final DeferredItem<Item> COW_CATCHER_BROWN;
	public static final DeferredItem<Item> COW_CATCHER_RED;
	public static final DeferredItem<Item> COW_CATCHER_ORANGE;
	public static final DeferredItem<Item> COW_CATCHER_YELLOW;
	public static final DeferredItem<Item> COW_CATCHER_LIME;
	public static final DeferredItem<Item> COW_CATCHER_GREEN;
	public static final DeferredItem<Item> COW_CATCHER_CYAN;
	public static final DeferredItem<Item> COW_CATCHER_LIGHT_BLUE;
	public static final DeferredItem<Item> COW_CATCHER_BLUE;
	public static final DeferredItem<Item> COW_CATCHER_PURPLE;
	public static final DeferredItem<Item> COW_CATCHER_MAGENTA;
	public static final DeferredItem<Item> COW_CATCHER_PINK;
	public static final DeferredItem<Item> MAGENTA_SCREEN;
	public static final DeferredItem<Item> ULTRA_WHITE;
	public static final DeferredItem<Item> STARS;
	public static final DeferredItem<Item> VOCAL_LABREPAIR;
	public static final DeferredItem<Item> VOCAL_EXPERIMENT;
	public static final DeferredItem<Item> VOCAL_REACTORBREACH;
	public static final DeferredItem<Item> VOCAL_SYSTEMS_LOADING;
	public static final DeferredItem<Item> VOCAL_DECONTAMINATION;
	public static final DeferredItem<Item> VOCAL_DECOMPRESSION;
	public static final DeferredItem<Item> VOCAL_LOCKDOWN;
	public static final DeferredItem<Item> VOCAL_LIFESYSTEMS_FAIL;
	public static final DeferredItem<Item> VOCAL_LEAVE_FACILITY;
	public static final DeferredItem<Item> VOCAL_UNAUTHORIZED_ACTIVITY;
	public static final DeferredItem<Item> VOCAL_EVACUATE_COMPLEX;
	public static final DeferredItem<Item> VOCAL_ATTENTION;
	public static final DeferredItem<Item> VOCAL_WARNING;
	public static final DeferredItem<Item> VOCAL_ALERT;
	public static final DeferredItem<Item> VOCAL_NUKE_ALERT;
	public static final DeferredItem<Item> VOCAL_EMERGENCY_EXIT;
	public static final DeferredItem<Item> VOCAL_SECURITY_BREACH;
	public static final DeferredItem<Item> THOMAS_FACE;
	public static final DeferredItem<Item> RED_CIRCUIT_BEE_NEST;
	public static final DeferredItem<Item> RED_CIRCUIT_CAMPFIRE;
	public static final DeferredItem<Item> RED_CIRCUIT_FIRE_CHARGE;
	public static final DeferredItem<Item> RED_CIRCUIT_FIREWORK;
	public static final DeferredItem<Item> RED_CIRCUIT_FLINT_AND_STEEL;
	public static final DeferredItem<Item> RED_CIRCUIT_LAVA_BUCKET;
	public static final DeferredItem<Item> RED_CIRCUIT_SMALL_SMOKE;
	public static final DeferredItem<Item> RED_CIRCUIT_STEAM;
	public static final DeferredItem<Item> RED_CIRCUIT_TNT;
	public static final DeferredItem<Item> RED_CIRCUIT_WATER_BUCKET;
	public static final DeferredItem<Item> BEE_NEST_PASSIVE_GENERATOR;
	public static final DeferredItem<Item> CAMPFIRE_PASSIVE_GENERATOR;
	public static final DeferredItem<Item> FIRE_CHARGE_PASSIVE_GENERATOR;
	public static final DeferredItem<Item> FIREWORK_PASSIVE_GENERATOR;
	public static final DeferredItem<Item> FLINT_AND_STEEL_PASSIVE_GENERATOR;
	public static final DeferredItem<Item> LAVA_BUCKET_PASSIVE_GENERATOR;
	public static final DeferredItem<Item> SMALL_SMOKE_PASSIVE_GENERATOR;
	public static final DeferredItem<Item> STEAM_PASSIVE_GENERATOR;
	public static final DeferredItem<Item> TNT_PASSIVE_GENERATOR;
	public static final DeferredItem<Item> WATER_BUCKET_PASSIVE_GENERATOR;
	public static final DeferredItem<Item> ENGINE_PISTON;
	public static final DeferredItem<Item> HELMS;
	public static final DeferredItem<Item> LIGHT_GRAY_SCREEN;
	public static final DeferredItem<Item> GRAY_SCREEN;
	public static final DeferredItem<Item> BROWN_SCREEN;
	public static final DeferredItem<Item> RED_SCREEN;
	public static final DeferredItem<Item> ORANGE_SCREEN;
	public static final DeferredItem<Item> YELLOW_SCREEN;
	public static final DeferredItem<Item> DARK_GREEN_SCREEN;
	public static final DeferredItem<Item> CYAN_SCREEN;
	public static final DeferredItem<Item> LIGHT_BLUE_SCREEN;
	public static final DeferredItem<Item> PURPLE_SCREEN;
	public static final DeferredItem<Item> PINK_SCREEN;
	public static final DeferredItem<Item> WHITE_BUFFER;
	public static final DeferredItem<Item> LIGHT_GRAY_BUFFER;
	public static final DeferredItem<Item> GRAY_BUFFER;
	public static final DeferredItem<Item> BLACK_BUFFER;
	public static final DeferredItem<Item> BROWN_BUFFER;
	public static final DeferredItem<Item> RED_BUFFER;
	public static final DeferredItem<Item> ORANGE_BUFFER;
	public static final DeferredItem<Item> YELLOW_BUFFER;
	public static final DeferredItem<Item> LIME_BUFFER;
	public static final DeferredItem<Item> GREEN_BUFFER;
	public static final DeferredItem<Item> CYAN_BUFFER;
	public static final DeferredItem<Item> LIGHT_BLUE_BUFFER;
	public static final DeferredItem<Item> BLUE_BUFFER;
	public static final DeferredItem<Item> PURPLE_BUFFER;
	public static final DeferredItem<Item> MAGENTA_BUFFER;
	public static final DeferredItem<Item> PINK_BUFFER;
	public static final DeferredItem<Item> GRANITE_BOILER;
	public static final DeferredItem<Item> DIORITE_BOILER;
	public static final DeferredItem<Item> RGB_STEEL_PLATING;
	public static final DeferredItem<Item> RGB_STEEL_TANK;
	public static final DeferredItem<Item> RGB_STEEL_SLAB;
	public static final DeferredItem<Item> RGB_STEEL_STAIRS;
	public static final DeferredItem<Item> RGB_STEEL_TRAPDOOR;
	public static final DeferredItem<Item> RGB_STEEL_WALL;
	public static final DeferredItem<Item> RGB_BOILER;
	public static final DeferredItem<Item> VENT_T;
	public static final DeferredItem<Item> VENT_T_UP;
	public static final DeferredItem<Item> LABORATORY_LEFT_ARROW_RED;
	public static final DeferredItem<Item> LABORATORY_RIGHT_ARROW_RED;
	public static final DeferredItem<Item> LABORATORY_ROMAN_1_RED;
	public static final DeferredItem<Item> LABORATORY_ROMAN_10_RED;
	public static final DeferredItem<Item> LABORATORY_ROMAN_5_RED;
	public static final DeferredItem<Item> LABORATORY_STRIPE_RED;
	public static final DeferredItem<Item> LABORATORY_LEFT_ARROW_LIME;
	public static final DeferredItem<Item> LABORATORY_RIGHT_ARROW_LIME;
	public static final DeferredItem<Item> LABORATORY_ROMAN_10_LIME;
	public static final DeferredItem<Item> LABORATORY_ROMAN_1_LIME;
	public static final DeferredItem<Item> LABORATORY_ROMAN_5_LIME;
	public static final DeferredItem<Item> LABORATORY_STRIPE_LIME;
	public static final DeferredItem<Item> RGB_BUFFER;
	public static final DeferredItem<Item> COW_CATCHER_RGB;
	public static final DeferredItem<Item> ANIMATED_SERVER_RACK;
	public static final DeferredItem<Item> WHITE_FUNNEL;
	public static final DeferredItem<Item> LIGHT_GRAY_FUNNEL;
	public static final DeferredItem<Item> GRAY_FUNNEL;
	public static final DeferredItem<Item> BLACK_FUNNEL;
	public static final DeferredItem<Item> BROWN_FUNNEL;
	public static final DeferredItem<Item> RED_FUNNEL;
	public static final DeferredItem<Item> ORANGE_FUNNEL;
	public static final DeferredItem<Item> YELLOW_FUNNEL;
	public static final DeferredItem<Item> LIME_FUNNEL;
	public static final DeferredItem<Item> GREEN_FUNNEL;
	public static final DeferredItem<Item> CYAN_FUNNEL;
	public static final DeferredItem<Item> LIGHT_BLUE_FUNNEL;
	public static final DeferredItem<Item> BLUE_FUNNEL;
	public static final DeferredItem<Item> PURPLE_FUNNEL;
	public static final DeferredItem<Item> MAGENTA_FUNNEL;
	public static final DeferredItem<Item> PINK_FUNNEL;
	public static final DeferredItem<Item> RGB_FUNNEL;
	public static final DeferredItem<Item> SMOKE_STACK_OPENING;
	static {
		LIGHTON = block(DavebuildingmodModBlocks.LIGHTON);
		LIGHTOFF = block(DavebuildingmodModBlocks.LIGHTOFF);
		ALARM_LIGHTOFF = block(DavebuildingmodModBlocks.ALARM_LIGHTOFF);
		ALARM_LIGHTON = block(DavebuildingmodModBlocks.ALARM_LIGHTON);
		GREEN_LIGHT_ON = block(DavebuildingmodModBlocks.GREEN_LIGHT_ON);
		GREEN_LIGHT_OFF = block(DavebuildingmodModBlocks.GREEN_LIGHT_OFF);
		BLUE_LIGHT_OFF = block(DavebuildingmodModBlocks.BLUE_LIGHT_OFF);
		BLUE_LIGHT_ON = block(DavebuildingmodModBlocks.BLUE_LIGHT_ON);
		SOUND_GENERATOR = block(DavebuildingmodModBlocks.SOUND_GENERATOR);
		PARTICLE_GENERATOR = block(DavebuildingmodModBlocks.PARTICLE_GENERATOR);
		STRIPEDBLOCK = block(DavebuildingmodModBlocks.STRIPEDBLOCK);
		ALARM_BLOCK = block(DavebuildingmodModBlocks.ALARM_BLOCK);
		RADIATION_BLOCK = block(DavebuildingmodModBlocks.RADIATION_BLOCK);
		BIOHAZARD_BLOCK = block(DavebuildingmodModBlocks.BIOHAZARD_BLOCK);
		DEATH_BLOCK = block(DavebuildingmodModBlocks.DEATH_BLOCK);
		ELECTRICITY_BLOCK = block(DavebuildingmodModBlocks.ELECTRICITY_BLOCK);
		CROSS_BLOCK = block(DavebuildingmodModBlocks.CROSS_BLOCK);
		BASIC_CIRCUIT = REGISTRY.register("basic_circuit", BasicCircuitItem::new);
		ADVANCED_CIRCUIT = REGISTRY.register("advanced_circuit", AdvancedCircuitItem::new);
		STRIPPEDBLOCK_HORIZONTAL = block(DavebuildingmodModBlocks.STRIPPEDBLOCK_HORIZONTAL);
		STEEL_INGOT = REGISTRY.register("steel_ingot", SteelIngotItem::new);
		STEEL_PLATING = block(DavebuildingmodModBlocks.STEEL_PLATING);
		STEEL_TILES = block(DavebuildingmodModBlocks.STEEL_TILES);
		STEEL_PILLAR = block(DavebuildingmodModBlocks.STEEL_PILLAR);
		STEEL_SEEMLESS = block(DavebuildingmodModBlocks.STEEL_SEEMLESS);
		STEEL_DOOR = doubleBlock(DavebuildingmodModBlocks.STEEL_DOOR);
		STEEL_TRAPDOOR = block(DavebuildingmodModBlocks.STEEL_TRAPDOOR);
		STEEL_STAIRS = block(DavebuildingmodModBlocks.STEEL_STAIRS);
		STEEL_SLAB = block(DavebuildingmodModBlocks.STEEL_SLAB);
		STEEL_WALL = block(DavebuildingmodModBlocks.STEEL_WALL);
		VENT_STRAIGHT = block(DavebuildingmodModBlocks.VENT_STRAIGHT);
		VENT_L = block(DavebuildingmodModBlocks.VENT_L);
		VENT_L_UP = block(DavebuildingmodModBlocks.VENT_L_UP);
		PC_SETUP = block(DavebuildingmodModBlocks.PC_SETUP);
		COMPUTER_TERMINAL = block(DavebuildingmodModBlocks.COMPUTER_TERMINAL);
		SERVER_RACK = block(DavebuildingmodModBlocks.SERVER_RACK);
		EXIT_SIGN = block(DavebuildingmodModBlocks.EXIT_SIGN);
		BLACK_QUILTED_WOOL = block(DavebuildingmodModBlocks.BLACK_QUILTED_WOOL);
		SOFT_AIR = block(DavebuildingmodModBlocks.SOFT_AIR);
		LABORATORY_BLOCK = block(DavebuildingmodModBlocks.LABORATORY_BLOCK);
		LABORATORY_VENT = block(DavebuildingmodModBlocks.LABORATORY_VENT);
		LABORATORY_PANEL = block(DavebuildingmodModBlocks.LABORATORY_PANEL);
		LABORATORY_STRIPE = block(DavebuildingmodModBlocks.LABORATORY_STRIPE);
		COPPER_COIL = block(DavebuildingmodModBlocks.COPPER_COIL);
		ISOLINEAR_FRONT_BLUE = block(DavebuildingmodModBlocks.ISOLINEAR_FRONT_BLUE);
		ISOLINEAR_MIDDLE_BLUE = block(DavebuildingmodModBlocks.ISOLINEAR_MIDDLE_BLUE);
		ISOLINEAR_BACK_BLUE = block(DavebuildingmodModBlocks.ISOLINEAR_BACK_BLUE);
		CUT_LABORATORY_BLOCK = block(DavebuildingmodModBlocks.CUT_LABORATORY_BLOCK);
		VOCALS_GENERATOR = block(DavebuildingmodModBlocks.VOCALS_GENERATOR);
		VOCAL_EMPTY = REGISTRY.register("vocal_empty", VocalEmptyItem::new);
		REINFORCED_GLASS = block(DavebuildingmodModBlocks.REINFORCED_GLASS);
		LABORATORY_ROMAN_1 = block(DavebuildingmodModBlocks.LABORATORY_ROMAN_1);
		LABORATORY_ROMAN_5 = block(DavebuildingmodModBlocks.LABORATORY_ROMAN_5);
		LABORATORY_ROMAN_10 = block(DavebuildingmodModBlocks.LABORATORY_ROMAN_10);
		ISOLINEAR_BACK_RED = block(DavebuildingmodModBlocks.ISOLINEAR_BACK_RED);
		ISOLINEAR_BACK_GREEN = block(DavebuildingmodModBlocks.ISOLINEAR_BACK_GREEN);
		ISOLINEAR_FRONT_GREEN = block(DavebuildingmodModBlocks.ISOLINEAR_FRONT_GREEN);
		ISOLINEAR_FRONT_RED = block(DavebuildingmodModBlocks.ISOLINEAR_FRONT_RED);
		ISOLINEAR_MIDDLE_RED = block(DavebuildingmodModBlocks.ISOLINEAR_MIDDLE_RED);
		ISOLINEAR_MIDDLE_GREEN = block(DavebuildingmodModBlocks.ISOLINEAR_MIDDLE_GREEN);
		ONEWAY_STONE = block(DavebuildingmodModBlocks.ONEWAY_STONE);
		VANTA_BLACK = block(DavebuildingmodModBlocks.VANTA_BLACK);
		GREEN_SCREEN = block(DavebuildingmodModBlocks.GREEN_SCREEN);
		BLUE_SCREEN = block(DavebuildingmodModBlocks.BLUE_SCREEN);
		ONEWAY_LABORATORY_BLOCK = block(DavebuildingmodModBlocks.ONEWAY_LABORATORY_BLOCK);
		RUBBER_DUCK = block(DavebuildingmodModBlocks.RUBBER_DUCK);
		FULL_LOG_PILE = block(DavebuildingmodModBlocks.FULL_LOG_PILE);
		LOG_PILE_1_TOP = block(DavebuildingmodModBlocks.LOG_PILE_1_TOP);
		LOG_PILE_2_BOTTOM = block(DavebuildingmodModBlocks.LOG_PILE_2_BOTTOM);
		LOG_PILE_2_TOP = block(DavebuildingmodModBlocks.LOG_PILE_2_TOP);
		LOG_PILE_1_BOTTOM = block(DavebuildingmodModBlocks.LOG_PILE_1_BOTTOM);
		LOG_PALISADE = block(DavebuildingmodModBlocks.LOG_PALISADE);
		BOOK_1 = block(DavebuildingmodModBlocks.BOOK_1);
		BOOK_2 = block(DavebuildingmodModBlocks.BOOK_2);
		SKELETON_1 = block(DavebuildingmodModBlocks.SKELETON_1);
		SKELETON_2 = block(DavebuildingmodModBlocks.SKELETON_2);
		SKELETON_3 = block(DavebuildingmodModBlocks.SKELETON_3);
		SKELETON_4 = block(DavebuildingmodModBlocks.SKELETON_4);
		YELLOW_ARROW_LEFT = block(DavebuildingmodModBlocks.YELLOW_ARROW_LEFT);
		YELLOW_ARROW_RIGHT = block(DavebuildingmodModBlocks.YELLOW_ARROW_RIGHT);
		LABORATORY_LEFT_ARROW = block(DavebuildingmodModBlocks.LABORATORY_LEFT_ARROW);
		LABORATORY_RIGHT_ARROW = block(DavebuildingmodModBlocks.LABORATORY_RIGHT_ARROW);
		LOG_PILE_CHAIR = block(DavebuildingmodModBlocks.LOG_PILE_CHAIR);
		BLUE_QUILTED_WOOL = block(DavebuildingmodModBlocks.BLUE_QUILTED_WOOL);
		BROWN_QUILTED_WOOL = block(DavebuildingmodModBlocks.BROWN_QUILTED_WOOL);
		CYAN_QUILTED_WOOL = block(DavebuildingmodModBlocks.CYAN_QUILTED_WOOL);
		GRAY_QUILTED_WOOL = block(DavebuildingmodModBlocks.GRAY_QUILTED_WOOL);
		GREEN_QUILTED_WOOL = block(DavebuildingmodModBlocks.GREEN_QUILTED_WOOL);
		LIGHT_BLUE_QUILTED_WOOL = block(DavebuildingmodModBlocks.LIGHT_BLUE_QUILTED_WOOL);
		LIGHT_GRAY_QUILTED_WOOL = block(DavebuildingmodModBlocks.LIGHT_GRAY_QUILTED_WOOL);
		LIME_QUILTED_WOOL = block(DavebuildingmodModBlocks.LIME_QUILTED_WOOL);
		MAGENTA_QUILTED_WOOL = block(DavebuildingmodModBlocks.MAGENTA_QUILTED_WOOL);
		ORANGE_QUILTED_WOOL = block(DavebuildingmodModBlocks.ORANGE_QUILTED_WOOL);
		PINK_QUILTED_WOOL = block(DavebuildingmodModBlocks.PINK_QUILTED_WOOL);
		PURPLE_QUILTED_WOOL = block(DavebuildingmodModBlocks.PURPLE_QUILTED_WOOL);
		RED_QUILTED_WOOL = block(DavebuildingmodModBlocks.RED_QUILTED_WOOL);
		WHITE_QUILTED_WOOL = block(DavebuildingmodModBlocks.WHITE_QUILTED_WOOL);
		YELLOW_QUILTED_WOOL = block(DavebuildingmodModBlocks.YELLOW_QUILTED_WOOL);
		BLACK_CHAIR = block(DavebuildingmodModBlocks.BLACK_CHAIR);
		BLUE_CHAIR = block(DavebuildingmodModBlocks.BLUE_CHAIR);
		BROWN_CHAIR = block(DavebuildingmodModBlocks.BROWN_CHAIR);
		CYAN_CHAIR = block(DavebuildingmodModBlocks.CYAN_CHAIR);
		GRAY_CHAIR = block(DavebuildingmodModBlocks.GRAY_CHAIR);
		GREEN_CHAIR = block(DavebuildingmodModBlocks.GREEN_CHAIR);
		LIGHT_BLUE_CHAIR = block(DavebuildingmodModBlocks.LIGHT_BLUE_CHAIR);
		LIGHT_GRAY_CHAIR = block(DavebuildingmodModBlocks.LIGHT_GRAY_CHAIR);
		LIME_CHAIR = block(DavebuildingmodModBlocks.LIME_CHAIR);
		MAGENTA_CHAIR = block(DavebuildingmodModBlocks.MAGENTA_CHAIR);
		ORANGE_CHAIR = block(DavebuildingmodModBlocks.ORANGE_CHAIR);
		PINK_CHAIR = block(DavebuildingmodModBlocks.PINK_CHAIR);
		PURPLE_CHAIR = block(DavebuildingmodModBlocks.PURPLE_CHAIR);
		RED_CHAIR = block(DavebuildingmodModBlocks.RED_CHAIR);
		WHITE_CHAIR = block(DavebuildingmodModBlocks.WHITE_CHAIR);
		YELLOW_CHAIR = block(DavebuildingmodModBlocks.YELLOW_CHAIR);
		HALF_LUMBER_DIAGONAL_LEFT = block(DavebuildingmodModBlocks.HALF_LUMBER_DIAGONAL_LEFT);
		HALF_LUMBER_DIAGONAL_RIGHT = block(DavebuildingmodModBlocks.HALF_LUMBER_DIAGONAL_RIGHT);
		HALF_LUMBER_VERTICAL = block(DavebuildingmodModBlocks.HALF_LUMBER_VERTICAL);
		HALF_LUMBER_HORIZONTAL = block(DavebuildingmodModBlocks.HALF_LUMBER_HORIZONTAL);
		HALF_LUMBER_BORDER = block(DavebuildingmodModBlocks.HALF_LUMBER_BORDER);
		HALF_LUMBER_BRICK_BORDER = block(DavebuildingmodModBlocks.HALF_LUMBER_BRICK_BORDER);
		HALF_LUMBER_BRICK_DIAGONAL_LEFT = block(DavebuildingmodModBlocks.HALF_LUMBER_BRICK_DIAGONAL_LEFT);
		HALF_LUMBER_BRICK_DIAGONAL_RIGHT = block(DavebuildingmodModBlocks.HALF_LUMBER_BRICK_DIAGONAL_RIGHT);
		HALF_LUMBER_BRICK_HORIZONTAL = block(DavebuildingmodModBlocks.HALF_LUMBER_BRICK_HORIZONTAL);
		HALF_LUMBER_BRICK_VERTICAL = block(DavebuildingmodModBlocks.HALF_LUMBER_BRICK_VERTICAL);
		ROCKY_DIRT = block(DavebuildingmodModBlocks.ROCKY_DIRT);
		STEEL_FRAME = block(DavebuildingmodModBlocks.STEEL_FRAME);
		POLISHED_STEEL_PLATING = block(DavebuildingmodModBlocks.POLISHED_STEEL_PLATING);
		TUNGSTEN_CARBITE = block(DavebuildingmodModBlocks.TUNGSTEN_CARBITE);
		STEEL_COLOUMN = block(DavebuildingmodModBlocks.STEEL_COLOUMN);
		TRACK_END = block(DavebuildingmodModBlocks.TRACK_END);
		CREATE_BOILER = block(DavebuildingmodModBlocks.CREATE_BOILER);
		BLACK_BOILER = block(DavebuildingmodModBlocks.BLACK_BOILER);
		BLACK_STEEL_TANK = block(DavebuildingmodModBlocks.BLACK_STEEL_TANK);
		BLACK_STEEL_PLATING = block(DavebuildingmodModBlocks.BLACK_STEEL_PLATING);
		BLACK_STEEL_STAIRS = block(DavebuildingmodModBlocks.BLACK_STEEL_STAIRS);
		BLACK_STEEL_SLAB = block(DavebuildingmodModBlocks.BLACK_STEEL_SLAB);
		BLACK_STEEL_TRAPDOOR = block(DavebuildingmodModBlocks.BLACK_STEEL_TRAPDOOR);
		BLACK_STEEL_WALL = block(DavebuildingmodModBlocks.BLACK_STEEL_WALL);
		STEEL_GIRDER = block(DavebuildingmodModBlocks.STEEL_GIRDER);
		RED_STEEL_PLATING = block(DavebuildingmodModBlocks.RED_STEEL_PLATING);
		RED_STEEL_STAIRS = block(DavebuildingmodModBlocks.RED_STEEL_STAIRS);
		RED_STEEL_SLAB = block(DavebuildingmodModBlocks.RED_STEEL_SLAB);
		RED_STEEL_TRAPDOOR = block(DavebuildingmodModBlocks.RED_STEEL_TRAPDOOR);
		RED_STEEL_WALL = block(DavebuildingmodModBlocks.RED_STEEL_WALL);
		BLACK_GUILDER_STEEL_TANK = block(DavebuildingmodModBlocks.BLACK_GUILDER_STEEL_TANK);
		BLACK_GUILDED_BOILER = block(DavebuildingmodModBlocks.BLACK_GUILDED_BOILER);
		RED_GUILDED_STEEL_TANK = block(DavebuildingmodModBlocks.RED_GUILDED_STEEL_TANK);
		RED_STEEL_TANK = block(DavebuildingmodModBlocks.RED_STEEL_TANK);
		RED_BOILER = block(DavebuildingmodModBlocks.RED_BOILER);
		RED_GUILDED_BOILER = block(DavebuildingmodModBlocks.RED_GUILDED_BOILER);
		GREEN_GILDED_STEEL_TANK = block(DavebuildingmodModBlocks.GREEN_GILDED_STEEL_TANK);
		GREEN_STEEL_PLATING = block(DavebuildingmodModBlocks.GREEN_STEEL_PLATING);
		GREEN_STEEL_SLAB = block(DavebuildingmodModBlocks.GREEN_STEEL_SLAB);
		GREEN_STEEL_STAIRS = block(DavebuildingmodModBlocks.GREEN_STEEL_STAIRS);
		GREEN_STEEL_TANK = block(DavebuildingmodModBlocks.GREEN_STEEL_TANK);
		GREEN_STEEL_TRAPDOOR = block(DavebuildingmodModBlocks.GREEN_STEEL_TRAPDOOR);
		GREEN_STEEL_WALL = block(DavebuildingmodModBlocks.GREEN_STEEL_WALL);
		GREEN_BOILER = block(DavebuildingmodModBlocks.GREEN_BOILER);
		GREEN_GILDED_BOILER = block(DavebuildingmodModBlocks.GREEN_GILDED_BOILER);
		BROWN_GILDED_STEEL_TANK = block(DavebuildingmodModBlocks.BROWN_GILDED_STEEL_TANK);
		BROWN_STEEL_PLATING = block(DavebuildingmodModBlocks.BROWN_STEEL_PLATING);
		BROWN_STEEL_SLAB = block(DavebuildingmodModBlocks.BROWN_STEEL_SLAB);
		BROWN_STEEL_STAIRS = block(DavebuildingmodModBlocks.BROWN_STEEL_STAIRS);
		BROWN_STEEL_TANK = block(DavebuildingmodModBlocks.BROWN_STEEL_TANK);
		BROWN_STEEL_TRAPDOOR = block(DavebuildingmodModBlocks.BROWN_STEEL_TRAPDOOR);
		BROWN_STEEL_WALL = block(DavebuildingmodModBlocks.BROWN_STEEL_WALL);
		BROWN_BOILER = block(DavebuildingmodModBlocks.BROWN_BOILER);
		BROWN_GILDED_BOILER = block(DavebuildingmodModBlocks.BROWN_GILDED_BOILER);
		BLUE_GILDED_STEEL_TANK = block(DavebuildingmodModBlocks.BLUE_GILDED_STEEL_TANK);
		BLUE_STEEL_PLATING = block(DavebuildingmodModBlocks.BLUE_STEEL_PLATING);
		BLUE_STEEL_SLAB = block(DavebuildingmodModBlocks.BLUE_STEEL_SLAB);
		BLUE_STEEL_STAIRS = block(DavebuildingmodModBlocks.BLUE_STEEL_STAIRS);
		BLUE_STEEL_TANK = block(DavebuildingmodModBlocks.BLUE_STEEL_TANK);
		BLUE_STEEL_TRAPDOOR = block(DavebuildingmodModBlocks.BLUE_STEEL_TRAPDOOR);
		BLUE_STEEL_WALL = block(DavebuildingmodModBlocks.BLUE_STEEL_WALL);
		BLUE_BOILER = block(DavebuildingmodModBlocks.BLUE_BOILER);
		BLUE_GILDED_BOILER = block(DavebuildingmodModBlocks.BLUE_GILDED_BOILER);
		PURPLE_GILDED_STEEL_TANK = block(DavebuildingmodModBlocks.PURPLE_GILDED_STEEL_TANK);
		PURPLE_STEEL_PLATING = block(DavebuildingmodModBlocks.PURPLE_STEEL_PLATING);
		PURPLE_STEEL_SLAB = block(DavebuildingmodModBlocks.PURPLE_STEEL_SLAB);
		PURPLE_STEEL_STAIRS = block(DavebuildingmodModBlocks.PURPLE_STEEL_STAIRS);
		PURPLE_STEEL_TANK = block(DavebuildingmodModBlocks.PURPLE_STEEL_TANK);
		PURPLE_STEEL_TRAPDOOR = block(DavebuildingmodModBlocks.PURPLE_STEEL_TRAPDOOR);
		PURPLE_STEEL_WALL = block(DavebuildingmodModBlocks.PURPLE_STEEL_WALL);
		CYAN_GILDED_STEEL_TANK = block(DavebuildingmodModBlocks.CYAN_GILDED_STEEL_TANK);
		CYAN_STEEL_PLATING = block(DavebuildingmodModBlocks.CYAN_STEEL_PLATING);
		CYAN_STEEL_SLAB = block(DavebuildingmodModBlocks.CYAN_STEEL_SLAB);
		CYAN_STEEL_STAIRS = block(DavebuildingmodModBlocks.CYAN_STEEL_STAIRS);
		CYAN_STEEL_TANK = block(DavebuildingmodModBlocks.CYAN_STEEL_TANK);
		CYAN_STEEL_TRAPDOOR = block(DavebuildingmodModBlocks.CYAN_STEEL_TRAPDOOR);
		CYAN_STEEL_WALL = block(DavebuildingmodModBlocks.CYAN_STEEL_WALL);
		PURPLE_BOILER = block(DavebuildingmodModBlocks.PURPLE_BOILER);
		PURPLE_GILDED_BOILER = block(DavebuildingmodModBlocks.PURPLE_GILDED_BOILER);
		CYAN_BOILER = block(DavebuildingmodModBlocks.CYAN_BOILER);
		CYAN_GILDED_BOILER = block(DavebuildingmodModBlocks.CYAN_GILDED_BOILER);
		LIGHT_GRAY_GILDED_STEEL_TANK = block(DavebuildingmodModBlocks.LIGHT_GRAY_GILDED_STEEL_TANK);
		LIGHT_GRAY_STEEL_PLATING = block(DavebuildingmodModBlocks.LIGHT_GRAY_STEEL_PLATING);
		LIGHT_GRAY_STEEL_SLAB = block(DavebuildingmodModBlocks.LIGHT_GRAY_STEEL_SLAB);
		LIGHT_GRAY_STEEL_STAIRS = block(DavebuildingmodModBlocks.LIGHT_GRAY_STEEL_STAIRS);
		LIGHT_GRAY_STEEL_TANK = block(DavebuildingmodModBlocks.LIGHT_GRAY_STEEL_TANK);
		LIGHT_GRAY_STEEL_TRAPDOOR = block(DavebuildingmodModBlocks.LIGHT_GRAY_STEEL_TRAPDOOR);
		LIGHT_GRAY_STEEL_WALL = block(DavebuildingmodModBlocks.LIGHT_GRAY_STEEL_WALL);
		LIGHT_GRAY_BOILER = block(DavebuildingmodModBlocks.LIGHT_GRAY_BOILER);
		LIGHT_GRAY_GILDED_BOILER = block(DavebuildingmodModBlocks.LIGHT_GRAY_GILDED_BOILER);
		GRAY_GILDED_STEEL_TANK = block(DavebuildingmodModBlocks.GRAY_GILDED_STEEL_TANK);
		GRAY_STEEL_PLATING = block(DavebuildingmodModBlocks.GRAY_STEEL_PLATING);
		GRAY_STEEL_SLAB = block(DavebuildingmodModBlocks.GRAY_STEEL_SLAB);
		GRAY_STEEL_STAIRS = block(DavebuildingmodModBlocks.GRAY_STEEL_STAIRS);
		GRAY_STEEL_TANK = block(DavebuildingmodModBlocks.GRAY_STEEL_TANK);
		GRAY_STEEL_TRAPDOOR = block(DavebuildingmodModBlocks.GRAY_STEEL_TRAPDOOR);
		GRAY_STEEL_WALL = block(DavebuildingmodModBlocks.GRAY_STEEL_WALL);
		GRAY_BOILER = block(DavebuildingmodModBlocks.GRAY_BOILER);
		GRAY_GILDED_BOILER = block(DavebuildingmodModBlocks.GRAY_GILDED_BOILER);
		PINK_GILDED_STEEL_TANK = block(DavebuildingmodModBlocks.PINK_GILDED_STEEL_TANK);
		PINK_STEEL_PLATING = block(DavebuildingmodModBlocks.PINK_STEEL_PLATING);
		PINK_STEEL_SLAB = block(DavebuildingmodModBlocks.PINK_STEEL_SLAB);
		PINK_STEEL_STAIRS = block(DavebuildingmodModBlocks.PINK_STEEL_STAIRS);
		PINK_STEEL_TANK = block(DavebuildingmodModBlocks.PINK_STEEL_TANK);
		PINK_STEEL_TRAPDOOR = block(DavebuildingmodModBlocks.PINK_STEEL_TRAPDOOR);
		PINK_STEEL_WALL = block(DavebuildingmodModBlocks.PINK_STEEL_WALL);
		LIME_GILDED_STEEL_TANK = block(DavebuildingmodModBlocks.LIME_GILDED_STEEL_TANK);
		LIME_STEEL_PLATING = block(DavebuildingmodModBlocks.LIME_STEEL_PLATING);
		LIME_STEEL_SLAB = block(DavebuildingmodModBlocks.LIME_STEEL_SLAB);
		LIME_STEEL_STAIRS = block(DavebuildingmodModBlocks.LIME_STEEL_STAIRS);
		LIME_STEEL_TANK = block(DavebuildingmodModBlocks.LIME_STEEL_TANK);
		LIME_STEEL_TRAPDOOR = block(DavebuildingmodModBlocks.LIME_STEEL_TRAPDOOR);
		LIME_STEEL_WALL = block(DavebuildingmodModBlocks.LIME_STEEL_WALL);
		PINK_BOILER = block(DavebuildingmodModBlocks.PINK_BOILER);
		PINK_GILDED_BOILER = block(DavebuildingmodModBlocks.PINK_GILDED_BOILER);
		LIME_BOILER = block(DavebuildingmodModBlocks.LIME_BOILER);
		LIME_GILDED_BOILER = block(DavebuildingmodModBlocks.LIME_GILDED_BOILER);
		YELLOW_GILDED_STEEL_TANK = block(DavebuildingmodModBlocks.YELLOW_GILDED_STEEL_TANK);
		YELLOW_STEEL_PLATING = block(DavebuildingmodModBlocks.YELLOW_STEEL_PLATING);
		YELLOW_STEEL_SLAB = block(DavebuildingmodModBlocks.YELLOW_STEEL_SLAB);
		YELLOW_STEEL_STAIRS = block(DavebuildingmodModBlocks.YELLOW_STEEL_STAIRS);
		YELLOW_STEEL_TANK = block(DavebuildingmodModBlocks.YELLOW_STEEL_TANK);
		YELLOW_STEEL_TRAPDOOR = block(DavebuildingmodModBlocks.YELLOW_STEEL_TRAPDOOR);
		YELLOW_STEEL_WALL = block(DavebuildingmodModBlocks.YELLOW_STEEL_WALL);
		YELLOW_BOILER = block(DavebuildingmodModBlocks.YELLOW_BOILER);
		YELLOW_GILDED_BOILER = block(DavebuildingmodModBlocks.YELLOW_GILDED_BOILER);
		LIGHT_BLUE_GILDED_STEEL_TANK = block(DavebuildingmodModBlocks.LIGHT_BLUE_GILDED_STEEL_TANK);
		LIGHT_BLUE_STEEL_PLATING = block(DavebuildingmodModBlocks.LIGHT_BLUE_STEEL_PLATING);
		LIGHT_BLUE_STEEL_SLAB = block(DavebuildingmodModBlocks.LIGHT_BLUE_STEEL_SLAB);
		LIGHT_BLUE_STEEL_STAIRS = block(DavebuildingmodModBlocks.LIGHT_BLUE_STEEL_STAIRS);
		LIGHT_BLUE_STEEL_TANK = block(DavebuildingmodModBlocks.LIGHT_BLUE_STEEL_TANK);
		LIGHT_BLUE_STEEL_TRAPDOOR = block(DavebuildingmodModBlocks.LIGHT_BLUE_STEEL_TRAPDOOR);
		LIGHT_BLUE_STEEL_WALL = block(DavebuildingmodModBlocks.LIGHT_BLUE_STEEL_WALL);
		MAGENTA_GILDED_STEEL_TANK = block(DavebuildingmodModBlocks.MAGENTA_GILDED_STEEL_TANK);
		MAGENTA_STEEL_PLATING = block(DavebuildingmodModBlocks.MAGENTA_STEEL_PLATING);
		MAGENTA_STEEL_SLAB = block(DavebuildingmodModBlocks.MAGENTA_STEEL_SLAB);
		MAGENTA_STEEL_STAIRS = block(DavebuildingmodModBlocks.MAGENTA_STEEL_STAIRS);
		MAGENTA_STEEL_TANK = block(DavebuildingmodModBlocks.MAGENTA_STEEL_TANK);
		MAGENTA_STEEL_TRAPDOOR = block(DavebuildingmodModBlocks.MAGENTA_STEEL_TRAPDOOR);
		MAGENTA_STEEL_WALL = block(DavebuildingmodModBlocks.MAGENTA_STEEL_WALL);
		MAGENTA_BOILER = block(DavebuildingmodModBlocks.MAGENTA_BOILER);
		MAGENTA_GILDED_BOILER = block(DavebuildingmodModBlocks.MAGENTA_GILDED_BOILER);
		ORANGE_GILDED_STEEL_TANK = block(DavebuildingmodModBlocks.ORANGE_GILDED_STEEL_TANK);
		ORANGE_STEEL_PLATING = block(DavebuildingmodModBlocks.ORANGE_STEEL_PLATING);
		ORANGE_STEEL_SLAB = block(DavebuildingmodModBlocks.ORANGE_STEEL_SLAB);
		ORANGE_STEEL_STAIRS = block(DavebuildingmodModBlocks.ORANGE_STEEL_STAIRS);
		ORANGE_STEEL_TANK = block(DavebuildingmodModBlocks.ORANGE_STEEL_TANK);
		ORANGE_STEEL_TRAPDOOR = block(DavebuildingmodModBlocks.ORANGE_STEEL_TRAPDOOR);
		ORANGE_STEEL_WALL = block(DavebuildingmodModBlocks.ORANGE_STEEL_WALL);
		ORANGE_BOILER = block(DavebuildingmodModBlocks.ORANGE_BOILER);
		ORANGE_GILDED_BOILER = block(DavebuildingmodModBlocks.ORANGE_GILDED_BOILER);
		WHITE_GILDED_STEEL_TANK = block(DavebuildingmodModBlocks.WHITE_GILDED_STEEL_TANK);
		WHITE_STEEL_PLATING = block(DavebuildingmodModBlocks.WHITE_STEEL_PLATING);
		WHITE_STEEL_SLAB = block(DavebuildingmodModBlocks.WHITE_STEEL_SLAB);
		WHITE_STEEL_STAIRS = block(DavebuildingmodModBlocks.WHITE_STEEL_STAIRS);
		WHITE_STEEL_TANK = block(DavebuildingmodModBlocks.WHITE_STEEL_TANK);
		WHITE_STEEL_TRAPDOOR = block(DavebuildingmodModBlocks.WHITE_STEEL_TRAPDOOR);
		WHITE_STEEL_WALL = block(DavebuildingmodModBlocks.WHITE_STEEL_WALL);
		WHITE_BOILER = block(DavebuildingmodModBlocks.WHITE_BOILER);
		WHITE_GILDED_BOILER = block(DavebuildingmodModBlocks.WHITE_GILDED_BOILER);
		LIGHT_BLUE_BOILER = block(DavebuildingmodModBlocks.LIGHT_BLUE_BOILER);
		LIGHT_BLUE_GILDED_BOILER = block(DavebuildingmodModBlocks.LIGHT_BLUE_GILDED_BOILER);
		STRIPEDBLOCK_MIDDLE = block(DavebuildingmodModBlocks.STRIPEDBLOCK_MIDDLE);
		GREEN_CIRCUIT_TNT_1 = REGISTRY.register("green_circuit_tnt_1", GreenCircuitTNT1Item::new);
		GREEN_CIRCUIT_NUKE = REGISTRY.register("green_circuit_nuke", GreenCircuitNukeItem::new);
		GREEN_CIRCUIT_XP_DING = REGISTRY.register("green_circuit_xp_ding", GreenCircuitXpDingItem::new);
		GREEN_CIRCUIT_LEVEL_UP = REGISTRY.register("green_circuit_level_up", GreenCircuitLevelUpItem::new);
		GREEN_CIRCUIT_ITEM_BURN = REGISTRY.register("green_circuit_item_burn", GreenCircuitItemBurnItem::new);
		GREEN_CIRCUIT_FIRE_CHARGE = REGISTRY.register("green_circuit_fire_charge", GreenCircuitFireChargeItem::new);
		GREEN_CIRCUIT_ELYTRA_FLY = REGISTRY.register("green_circuit_elytra_fly", GreenCircuitElytraFlyItem::new);
		GREEN_CIRCUIT_BLAZE_HURT = REGISTRY.register("green_circuit_blaze_hurt", GreenCircuitBlazeHurtItem::new);
		GREEN_CIRCUIT_BAT_TAKEOFF = REGISTRY.register("green_circuit_bat_takeoff", GreenCircuitBatTakeoffItem::new);
		COMPUTER_TERMINAL_STEEL = block(DavebuildingmodModBlocks.COMPUTER_TERMINAL_STEEL);
		ROCKY_DIRT_SLAB = block(DavebuildingmodModBlocks.ROCKY_DIRT_SLAB);
		DIRT_SLAB = block(DavebuildingmodModBlocks.DIRT_SLAB);
		GRAVEL_SLAB = block(DavebuildingmodModBlocks.GRAVEL_SLAB);
		BALLAST = block(DavebuildingmodModBlocks.BALLAST);
		BALLAST_SLAB = block(DavebuildingmodModBlocks.BALLAST_SLAB);
		SKELETON_5 = block(DavebuildingmodModBlocks.SKELETON_5);
		SKELETON_6 = block(DavebuildingmodModBlocks.SKELETON_6);
		ARROW_UP_SIGN = block(DavebuildingmodModBlocks.ARROW_UP_SIGN);
		ARROW_RIGHT_SIGN = block(DavebuildingmodModBlocks.ARROW_RIGHT_SIGN);
		ARROW_LEFT_SIGN = block(DavebuildingmodModBlocks.ARROW_LEFT_SIGN);
		ARROW_DOWN_SIGN = block(DavebuildingmodModBlocks.ARROW_DOWN_SIGN);
		ARROW_RETURN_SIGN = block(DavebuildingmodModBlocks.ARROW_RETURN_SIGN);
		NO_ENTRY_SIGN = block(DavebuildingmodModBlocks.NO_ENTRY_SIGN);
		ALARM_SIGN = block(DavebuildingmodModBlocks.ALARM_SIGN);
		ONEWAY_SIGN = block(DavebuildingmodModBlocks.ONEWAY_SIGN);
		STEEL_BLOCK = block(DavebuildingmodModBlocks.STEEL_BLOCK);
		HELPER_PAPER = REGISTRY.register("helper_paper", HelperPaperItem::new);
		STEEL_MESH_TRAPDOOR = block(DavebuildingmodModBlocks.STEEL_MESH_TRAPDOOR);
		COPPER_BOILER = block(DavebuildingmodModBlocks.COPPER_BOILER);
		BRASS_BOILER = block(DavebuildingmodModBlocks.BRASS_BOILER);
		ZINC_BOILER = block(DavebuildingmodModBlocks.ZINC_BOILER);
		GAUGE_OUTER = block(DavebuildingmodModBlocks.GAUGE_OUTER);
		GAUGE_INNER = block(DavebuildingmodModBlocks.GAUGE_INNER);
		COW_CATCHER_WHITE = block(DavebuildingmodModBlocks.COW_CATCHER_WHITE);
		COW_CATCHER_LIGHT_GRAY = block(DavebuildingmodModBlocks.COW_CATCHER_LIGHT_GRAY);
		COW_CATCHER_GRAY = block(DavebuildingmodModBlocks.COW_CATCHER_GRAY);
		COW_CATCHER_BLACK = block(DavebuildingmodModBlocks.COW_CATCHER_BLACK);
		COW_CATCHER_BROWN = block(DavebuildingmodModBlocks.COW_CATCHER_BROWN);
		COW_CATCHER_RED = block(DavebuildingmodModBlocks.COW_CATCHER_RED);
		COW_CATCHER_ORANGE = block(DavebuildingmodModBlocks.COW_CATCHER_ORANGE);
		COW_CATCHER_YELLOW = block(DavebuildingmodModBlocks.COW_CATCHER_YELLOW);
		COW_CATCHER_LIME = block(DavebuildingmodModBlocks.COW_CATCHER_LIME);
		COW_CATCHER_GREEN = block(DavebuildingmodModBlocks.COW_CATCHER_GREEN);
		COW_CATCHER_CYAN = block(DavebuildingmodModBlocks.COW_CATCHER_CYAN);
		COW_CATCHER_LIGHT_BLUE = block(DavebuildingmodModBlocks.COW_CATCHER_LIGHT_BLUE);
		COW_CATCHER_BLUE = block(DavebuildingmodModBlocks.COW_CATCHER_BLUE);
		COW_CATCHER_PURPLE = block(DavebuildingmodModBlocks.COW_CATCHER_PURPLE);
		COW_CATCHER_MAGENTA = block(DavebuildingmodModBlocks.COW_CATCHER_MAGENTA);
		COW_CATCHER_PINK = block(DavebuildingmodModBlocks.COW_CATCHER_PINK);
		MAGENTA_SCREEN = block(DavebuildingmodModBlocks.MAGENTA_SCREEN);
		ULTRA_WHITE = block(DavebuildingmodModBlocks.ULTRA_WHITE);
		STARS = block(DavebuildingmodModBlocks.STARS);
		VOCAL_LABREPAIR = REGISTRY.register("vocal_labrepair", VocalLabrepairItem::new);
		VOCAL_EXPERIMENT = REGISTRY.register("vocal_experiment", VocalExperimentItem::new);
		VOCAL_REACTORBREACH = REGISTRY.register("vocal_reactorbreach", VocalReactorbreachItem::new);
		VOCAL_SYSTEMS_LOADING = REGISTRY.register("vocal_systems_loading", VocalSystemsLoadingItem::new);
		VOCAL_DECONTAMINATION = REGISTRY.register("vocal_decontamination", VocalDecontaminationItem::new);
		VOCAL_DECOMPRESSION = REGISTRY.register("vocal_decompression", VocalDecompressionItem::new);
		VOCAL_LOCKDOWN = REGISTRY.register("vocal_lockdown", VocalLockdownItem::new);
		VOCAL_LIFESYSTEMS_FAIL = REGISTRY.register("vocal_lifesystems_fail", VocalLifesystemsFailItem::new);
		VOCAL_LEAVE_FACILITY = REGISTRY.register("vocal_leave_facility", VocalLeaveFacilityItem::new);
		VOCAL_UNAUTHORIZED_ACTIVITY = REGISTRY.register("vocal_unauthorized_activity", VocalUnauthorizedActivityItem::new);
		VOCAL_EVACUATE_COMPLEX = REGISTRY.register("vocal_evacuate_complex", VocalEvacuateComplexItem::new);
		VOCAL_ATTENTION = REGISTRY.register("vocal_attention", VocalAttentionItem::new);
		VOCAL_WARNING = REGISTRY.register("vocal_warning", VocalWarningItem::new);
		VOCAL_ALERT = REGISTRY.register("vocal_alert", VocalAlertItem::new);
		VOCAL_NUKE_ALERT = REGISTRY.register("vocal_nuke_alert", VocalNukeAlertItem::new);
		VOCAL_EMERGENCY_EXIT = REGISTRY.register("vocal_emergency_exit", VocalEmergencyExitItem::new);
		VOCAL_SECURITY_BREACH = REGISTRY.register("vocal_security_breach", VocalSecurityBreachItem::new);
		THOMAS_FACE = block(DavebuildingmodModBlocks.THOMAS_FACE);
		RED_CIRCUIT_BEE_NEST = REGISTRY.register("red_circuit_bee_nest", RedCircuitBeeNestItem::new);
		RED_CIRCUIT_CAMPFIRE = REGISTRY.register("red_circuit_campfire", RedCircuitCampfireItem::new);
		RED_CIRCUIT_FIRE_CHARGE = REGISTRY.register("red_circuit_fire_charge", RedCircuitFireChargeItem::new);
		RED_CIRCUIT_FIREWORK = REGISTRY.register("red_circuit_firework", RedCircuitFireworkItem::new);
		RED_CIRCUIT_FLINT_AND_STEEL = REGISTRY.register("red_circuit_flint_and_steel", RedCircuitFlintAndSteelItem::new);
		RED_CIRCUIT_LAVA_BUCKET = REGISTRY.register("red_circuit_lava_bucket", RedCircuitLavaBucketItem::new);
		RED_CIRCUIT_SMALL_SMOKE = REGISTRY.register("red_circuit_small_smoke", RedCircuitSmallSmokeItem::new);
		RED_CIRCUIT_STEAM = REGISTRY.register("red_circuit_steam", RedCircuitSteamItem::new);
		RED_CIRCUIT_TNT = REGISTRY.register("red_circuit_tnt", RedCircuitTntItem::new);
		RED_CIRCUIT_WATER_BUCKET = REGISTRY.register("red_circuit_water_bucket", RedCircuitWaterBucketItem::new);
		BEE_NEST_PASSIVE_GENERATOR = block(DavebuildingmodModBlocks.BEE_NEST_PASSIVE_GENERATOR);
		CAMPFIRE_PASSIVE_GENERATOR = block(DavebuildingmodModBlocks.CAMPFIRE_PASSIVE_GENERATOR);
		FIRE_CHARGE_PASSIVE_GENERATOR = block(DavebuildingmodModBlocks.FIRE_CHARGE_PASSIVE_GENERATOR);
		FIREWORK_PASSIVE_GENERATOR = block(DavebuildingmodModBlocks.FIREWORK_PASSIVE_GENERATOR);
		FLINT_AND_STEEL_PASSIVE_GENERATOR = block(DavebuildingmodModBlocks.FLINT_AND_STEEL_PASSIVE_GENERATOR);
		LAVA_BUCKET_PASSIVE_GENERATOR = block(DavebuildingmodModBlocks.LAVA_BUCKET_PASSIVE_GENERATOR);
		SMALL_SMOKE_PASSIVE_GENERATOR = block(DavebuildingmodModBlocks.SMALL_SMOKE_PASSIVE_GENERATOR);
		STEAM_PASSIVE_GENERATOR = block(DavebuildingmodModBlocks.STEAM_PASSIVE_GENERATOR);
		TNT_PASSIVE_GENERATOR = block(DavebuildingmodModBlocks.TNT_PASSIVE_GENERATOR);
		WATER_BUCKET_PASSIVE_GENERATOR = block(DavebuildingmodModBlocks.WATER_BUCKET_PASSIVE_GENERATOR);
		ENGINE_PISTON = block(DavebuildingmodModBlocks.ENGINE_PISTON);
		HELMS = block(DavebuildingmodModBlocks.HELMS);
		LIGHT_GRAY_SCREEN = block(DavebuildingmodModBlocks.LIGHT_GRAY_SCREEN);
		GRAY_SCREEN = block(DavebuildingmodModBlocks.GRAY_SCREEN);
		BROWN_SCREEN = block(DavebuildingmodModBlocks.BROWN_SCREEN);
		RED_SCREEN = block(DavebuildingmodModBlocks.RED_SCREEN);
		ORANGE_SCREEN = block(DavebuildingmodModBlocks.ORANGE_SCREEN);
		YELLOW_SCREEN = block(DavebuildingmodModBlocks.YELLOW_SCREEN);
		DARK_GREEN_SCREEN = block(DavebuildingmodModBlocks.DARK_GREEN_SCREEN);
		CYAN_SCREEN = block(DavebuildingmodModBlocks.CYAN_SCREEN);
		LIGHT_BLUE_SCREEN = block(DavebuildingmodModBlocks.LIGHT_BLUE_SCREEN);
		PURPLE_SCREEN = block(DavebuildingmodModBlocks.PURPLE_SCREEN);
		PINK_SCREEN = block(DavebuildingmodModBlocks.PINK_SCREEN);
		WHITE_BUFFER = block(DavebuildingmodModBlocks.WHITE_BUFFER);
		LIGHT_GRAY_BUFFER = block(DavebuildingmodModBlocks.LIGHT_GRAY_BUFFER);
		GRAY_BUFFER = block(DavebuildingmodModBlocks.GRAY_BUFFER);
		BLACK_BUFFER = block(DavebuildingmodModBlocks.BLACK_BUFFER);
		BROWN_BUFFER = block(DavebuildingmodModBlocks.BROWN_BUFFER);
		RED_BUFFER = block(DavebuildingmodModBlocks.RED_BUFFER);
		ORANGE_BUFFER = block(DavebuildingmodModBlocks.ORANGE_BUFFER);
		YELLOW_BUFFER = block(DavebuildingmodModBlocks.YELLOW_BUFFER);
		LIME_BUFFER = block(DavebuildingmodModBlocks.LIME_BUFFER);
		GREEN_BUFFER = block(DavebuildingmodModBlocks.GREEN_BUFFER);
		CYAN_BUFFER = block(DavebuildingmodModBlocks.CYAN_BUFFER);
		LIGHT_BLUE_BUFFER = block(DavebuildingmodModBlocks.LIGHT_BLUE_BUFFER);
		BLUE_BUFFER = block(DavebuildingmodModBlocks.BLUE_BUFFER);
		PURPLE_BUFFER = block(DavebuildingmodModBlocks.PURPLE_BUFFER);
		MAGENTA_BUFFER = block(DavebuildingmodModBlocks.MAGENTA_BUFFER);
		PINK_BUFFER = block(DavebuildingmodModBlocks.PINK_BUFFER);
		GRANITE_BOILER = block(DavebuildingmodModBlocks.GRANITE_BOILER);
		DIORITE_BOILER = block(DavebuildingmodModBlocks.DIORITE_BOILER);
		RGB_STEEL_PLATING = block(DavebuildingmodModBlocks.RGB_STEEL_PLATING);
		RGB_STEEL_TANK = block(DavebuildingmodModBlocks.RGB_STEEL_TANK);
		RGB_STEEL_SLAB = block(DavebuildingmodModBlocks.RGB_STEEL_SLAB);
		RGB_STEEL_STAIRS = block(DavebuildingmodModBlocks.RGB_STEEL_STAIRS);
		RGB_STEEL_TRAPDOOR = block(DavebuildingmodModBlocks.RGB_STEEL_TRAPDOOR);
		RGB_STEEL_WALL = block(DavebuildingmodModBlocks.RGB_STEEL_WALL);
		RGB_BOILER = block(DavebuildingmodModBlocks.RGB_BOILER);
		VENT_T = block(DavebuildingmodModBlocks.VENT_T);
		VENT_T_UP = block(DavebuildingmodModBlocks.VENT_T_UP);
		LABORATORY_LEFT_ARROW_RED = block(DavebuildingmodModBlocks.LABORATORY_LEFT_ARROW_RED);
		LABORATORY_RIGHT_ARROW_RED = block(DavebuildingmodModBlocks.LABORATORY_RIGHT_ARROW_RED);
		LABORATORY_ROMAN_1_RED = block(DavebuildingmodModBlocks.LABORATORY_ROMAN_1_RED);
		LABORATORY_ROMAN_10_RED = block(DavebuildingmodModBlocks.LABORATORY_ROMAN_10_RED);
		LABORATORY_ROMAN_5_RED = block(DavebuildingmodModBlocks.LABORATORY_ROMAN_5_RED);
		LABORATORY_STRIPE_RED = block(DavebuildingmodModBlocks.LABORATORY_STRIPE_RED);
		LABORATORY_LEFT_ARROW_LIME = block(DavebuildingmodModBlocks.LABORATORY_LEFT_ARROW_LIME);
		LABORATORY_RIGHT_ARROW_LIME = block(DavebuildingmodModBlocks.LABORATORY_RIGHT_ARROW_LIME);
		LABORATORY_ROMAN_10_LIME = block(DavebuildingmodModBlocks.LABORATORY_ROMAN_10_LIME);
		LABORATORY_ROMAN_1_LIME = block(DavebuildingmodModBlocks.LABORATORY_ROMAN_1_LIME);
		LABORATORY_ROMAN_5_LIME = block(DavebuildingmodModBlocks.LABORATORY_ROMAN_5_LIME);
		LABORATORY_STRIPE_LIME = block(DavebuildingmodModBlocks.LABORATORY_STRIPE_LIME);
		RGB_BUFFER = block(DavebuildingmodModBlocks.RGB_BUFFER);
		COW_CATCHER_RGB = block(DavebuildingmodModBlocks.COW_CATCHER_RGB);
		ANIMATED_SERVER_RACK = block(DavebuildingmodModBlocks.ANIMATED_SERVER_RACK);
		WHITE_FUNNEL = block(DavebuildingmodModBlocks.WHITE_FUNNEL);
		LIGHT_GRAY_FUNNEL = block(DavebuildingmodModBlocks.LIGHT_GRAY_FUNNEL);
		GRAY_FUNNEL = block(DavebuildingmodModBlocks.GRAY_FUNNEL);
		BLACK_FUNNEL = block(DavebuildingmodModBlocks.BLACK_FUNNEL);
		BROWN_FUNNEL = block(DavebuildingmodModBlocks.BROWN_FUNNEL);
		RED_FUNNEL = block(DavebuildingmodModBlocks.RED_FUNNEL);
		ORANGE_FUNNEL = block(DavebuildingmodModBlocks.ORANGE_FUNNEL);
		YELLOW_FUNNEL = block(DavebuildingmodModBlocks.YELLOW_FUNNEL);
		LIME_FUNNEL = block(DavebuildingmodModBlocks.LIME_FUNNEL);
		GREEN_FUNNEL = block(DavebuildingmodModBlocks.GREEN_FUNNEL);
		CYAN_FUNNEL = block(DavebuildingmodModBlocks.CYAN_FUNNEL);
		LIGHT_BLUE_FUNNEL = block(DavebuildingmodModBlocks.LIGHT_BLUE_FUNNEL);
		BLUE_FUNNEL = block(DavebuildingmodModBlocks.BLUE_FUNNEL);
		PURPLE_FUNNEL = block(DavebuildingmodModBlocks.PURPLE_FUNNEL);
		MAGENTA_FUNNEL = block(DavebuildingmodModBlocks.MAGENTA_FUNNEL);
		PINK_FUNNEL = block(DavebuildingmodModBlocks.PINK_FUNNEL);
		RGB_FUNNEL = block(DavebuildingmodModBlocks.RGB_FUNNEL);
		SMOKE_STACK_OPENING = block(DavebuildingmodModBlocks.SMOKE_STACK_OPENING);
	}

	// Start of user code block custom items
	// End of user code block custom items
	@SubscribeEvent
	public static void registerCapabilities(RegisterCapabilitiesEvent event) {
		event.registerItem(Capabilities.ItemHandler.ITEM, (stack, context) -> new HelperPaperInventoryCapability(stack), HELPER_PAPER.get());
	}

	private static DeferredItem<Item> block(DeferredHolder<Block, Block> block) {
		return block(block, new Item.Properties());
	}

	private static DeferredItem<Item> block(DeferredHolder<Block, Block> block, Item.Properties properties) {
		return REGISTRY.register(block.getId().getPath(), () -> new BlockItem(block.get(), properties));
	}

	private static DeferredItem<Item> doubleBlock(DeferredHolder<Block, Block> block) {
		return doubleBlock(block, new Item.Properties());
	}

	private static DeferredItem<Item> doubleBlock(DeferredHolder<Block, Block> block, Item.Properties properties) {
		return REGISTRY.register(block.getId().getPath(), () -> new DoubleHighBlockItem(block.get(), properties));
	}
}