/*
 *    MCreator note: This file will be REGENERATED on each build.
 */
package net.mcreator.buildingmod.init;

import net.neoforged.neoforge.registries.DeferredRegister;
import net.neoforged.neoforge.registries.DeferredBlock;

import net.minecraft.world.level.block.Block;

import net.mcreator.buildingmod.block.*;
import net.mcreator.buildingmod.DavebuildingmodMod;

public class DavebuildingmodModBlocks {
	public static final DeferredRegister.Blocks REGISTRY = DeferredRegister.createBlocks(DavebuildingmodMod.MODID);
	public static final DeferredBlock<Block> LIGHTON;
	public static final DeferredBlock<Block> LIGHTOFF;
	public static final DeferredBlock<Block> ALARM_LIGHTOFF;
	public static final DeferredBlock<Block> ALARM_LIGHTON;
	public static final DeferredBlock<Block> GREEN_LIGHT_ON;
	public static final DeferredBlock<Block> GREEN_LIGHT_OFF;
	public static final DeferredBlock<Block> BLUE_LIGHT_OFF;
	public static final DeferredBlock<Block> BLUE_LIGHT_ON;
	public static final DeferredBlock<Block> SOUND_GENERATOR;
	public static final DeferredBlock<Block> PARTICLE_GENERATOR;
	public static final DeferredBlock<Block> STRIPEDBLOCK;
	public static final DeferredBlock<Block> ALARM_BLOCK;
	public static final DeferredBlock<Block> RADIATION_BLOCK;
	public static final DeferredBlock<Block> BIOHAZARD_BLOCK;
	public static final DeferredBlock<Block> DEATH_BLOCK;
	public static final DeferredBlock<Block> ELECTRICITY_BLOCK;
	public static final DeferredBlock<Block> CROSS_BLOCK;
	public static final DeferredBlock<Block> STRIPPEDBLOCK_HORIZONTAL;
	public static final DeferredBlock<Block> STEEL_PLATING;
	public static final DeferredBlock<Block> STEEL_TILES;
	public static final DeferredBlock<Block> STEEL_PILLAR;
	public static final DeferredBlock<Block> STEEL_SEEMLESS;
	public static final DeferredBlock<Block> STEEL_DOOR;
	public static final DeferredBlock<Block> STEEL_TRAPDOOR;
	public static final DeferredBlock<Block> STEEL_STAIRS;
	public static final DeferredBlock<Block> STEEL_SLAB;
	public static final DeferredBlock<Block> STEEL_WALL;
	public static final DeferredBlock<Block> VENT_STRAIGHT;
	public static final DeferredBlock<Block> VENT_L;
	public static final DeferredBlock<Block> VENT_L_UP;
	public static final DeferredBlock<Block> PC_SETUP;
	public static final DeferredBlock<Block> COMPUTER_TERMINAL;
	public static final DeferredBlock<Block> SERVER_RACK;
	public static final DeferredBlock<Block> EXIT_SIGN;
	public static final DeferredBlock<Block> BLACK_QUILTED_WOOL;
	public static final DeferredBlock<Block> SOFT_AIR;
	public static final DeferredBlock<Block> LABORATORY_BLOCK;
	public static final DeferredBlock<Block> LABORATORY_VENT;
	public static final DeferredBlock<Block> LABORATORY_PANEL;
	public static final DeferredBlock<Block> LABORATORY_STRIPE;
	public static final DeferredBlock<Block> COPPER_COIL;
	public static final DeferredBlock<Block> ISOLINEAR_FRONT_BLUE;
	public static final DeferredBlock<Block> ISOLINEAR_MIDDLE_BLUE;
	public static final DeferredBlock<Block> ISOLINEAR_BACK_BLUE;
	public static final DeferredBlock<Block> CUT_LABORATORY_BLOCK;
	public static final DeferredBlock<Block> VOCALS_GENERATOR;
	public static final DeferredBlock<Block> REINFORCED_GLASS;
	public static final DeferredBlock<Block> LABORATORY_ROMAN_1;
	public static final DeferredBlock<Block> LABORATORY_ROMAN_5;
	public static final DeferredBlock<Block> LABORATORY_ROMAN_10;
	public static final DeferredBlock<Block> ISOLINEAR_BACK_RED;
	public static final DeferredBlock<Block> ISOLINEAR_BACK_GREEN;
	public static final DeferredBlock<Block> ISOLINEAR_FRONT_GREEN;
	public static final DeferredBlock<Block> ISOLINEAR_FRONT_RED;
	public static final DeferredBlock<Block> ISOLINEAR_MIDDLE_RED;
	public static final DeferredBlock<Block> ISOLINEAR_MIDDLE_GREEN;
	public static final DeferredBlock<Block> ONEWAY_STONE;
	public static final DeferredBlock<Block> VANTA_BLACK;
	public static final DeferredBlock<Block> GREEN_SCREEN;
	public static final DeferredBlock<Block> BLUE_SCREEN;
	public static final DeferredBlock<Block> ONEWAY_LABORATORY_BLOCK;
	public static final DeferredBlock<Block> RUBBER_DUCK;
	public static final DeferredBlock<Block> FULL_LOG_PILE;
	public static final DeferredBlock<Block> LOG_PILE_1_TOP;
	public static final DeferredBlock<Block> LOG_PILE_2_BOTTOM;
	public static final DeferredBlock<Block> LOG_PILE_2_TOP;
	public static final DeferredBlock<Block> LOG_PILE_1_BOTTOM;
	public static final DeferredBlock<Block> LOG_PALISADE;
	public static final DeferredBlock<Block> BOOK_1;
	public static final DeferredBlock<Block> BOOK_2;
	public static final DeferredBlock<Block> SKELETON_1;
	public static final DeferredBlock<Block> SKELETON_2;
	public static final DeferredBlock<Block> SKELETON_3;
	public static final DeferredBlock<Block> SKELETON_4;
	public static final DeferredBlock<Block> YELLOW_ARROW_LEFT;
	public static final DeferredBlock<Block> YELLOW_ARROW_RIGHT;
	public static final DeferredBlock<Block> LABORATORY_LEFT_ARROW;
	public static final DeferredBlock<Block> LABORATORY_RIGHT_ARROW;
	public static final DeferredBlock<Block> LOG_PILE_CHAIR;
	public static final DeferredBlock<Block> BLUE_QUILTED_WOOL;
	public static final DeferredBlock<Block> BROWN_QUILTED_WOOL;
	public static final DeferredBlock<Block> CYAN_QUILTED_WOOL;
	public static final DeferredBlock<Block> GRAY_QUILTED_WOOL;
	public static final DeferredBlock<Block> GREEN_QUILTED_WOOL;
	public static final DeferredBlock<Block> LIGHT_BLUE_QUILTED_WOOL;
	public static final DeferredBlock<Block> LIGHT_GRAY_QUILTED_WOOL;
	public static final DeferredBlock<Block> LIME_QUILTED_WOOL;
	public static final DeferredBlock<Block> MAGENTA_QUILTED_WOOL;
	public static final DeferredBlock<Block> ORANGE_QUILTED_WOOL;
	public static final DeferredBlock<Block> PINK_QUILTED_WOOL;
	public static final DeferredBlock<Block> PURPLE_QUILTED_WOOL;
	public static final DeferredBlock<Block> RED_QUILTED_WOOL;
	public static final DeferredBlock<Block> WHITE_QUILTED_WOOL;
	public static final DeferredBlock<Block> YELLOW_QUILTED_WOOL;
	public static final DeferredBlock<Block> BLACK_CHAIR;
	public static final DeferredBlock<Block> BLUE_CHAIR;
	public static final DeferredBlock<Block> BROWN_CHAIR;
	public static final DeferredBlock<Block> CYAN_CHAIR;
	public static final DeferredBlock<Block> GRAY_CHAIR;
	public static final DeferredBlock<Block> GREEN_CHAIR;
	public static final DeferredBlock<Block> LIGHT_BLUE_CHAIR;
	public static final DeferredBlock<Block> LIGHT_GRAY_CHAIR;
	public static final DeferredBlock<Block> LIME_CHAIR;
	public static final DeferredBlock<Block> MAGENTA_CHAIR;
	public static final DeferredBlock<Block> ORANGE_CHAIR;
	public static final DeferredBlock<Block> PINK_CHAIR;
	public static final DeferredBlock<Block> PURPLE_CHAIR;
	public static final DeferredBlock<Block> RED_CHAIR;
	public static final DeferredBlock<Block> WHITE_CHAIR;
	public static final DeferredBlock<Block> YELLOW_CHAIR;
	public static final DeferredBlock<Block> HALF_LUMBER_DIAGONAL_LEFT;
	public static final DeferredBlock<Block> HALF_LUMBER_DIAGONAL_RIGHT;
	public static final DeferredBlock<Block> HALF_LUMBER_VERTICAL;
	public static final DeferredBlock<Block> HALF_LUMBER_HORIZONTAL;
	public static final DeferredBlock<Block> HALF_LUMBER_BORDER;
	public static final DeferredBlock<Block> HALF_LUMBER_BRICK_BORDER;
	public static final DeferredBlock<Block> HALF_LUMBER_BRICK_DIAGONAL_LEFT;
	public static final DeferredBlock<Block> HALF_LUMBER_BRICK_DIAGONAL_RIGHT;
	public static final DeferredBlock<Block> HALF_LUMBER_BRICK_HORIZONTAL;
	public static final DeferredBlock<Block> HALF_LUMBER_BRICK_VERTICAL;
	public static final DeferredBlock<Block> ROCKY_DIRT;
	public static final DeferredBlock<Block> STEEL_FRAME;
	public static final DeferredBlock<Block> POLISHED_STEEL_PLATING;
	public static final DeferredBlock<Block> TUNGSTEN_CARBITE;
	public static final DeferredBlock<Block> STEEL_COLOUMN;
	public static final DeferredBlock<Block> TRACK_END;
	public static final DeferredBlock<Block> CREATE_BOILER;
	public static final DeferredBlock<Block> BLACK_BOILER;
	public static final DeferredBlock<Block> BLACK_STEEL_TANK;
	public static final DeferredBlock<Block> BLACK_STEEL_PLATING;
	public static final DeferredBlock<Block> BLACK_STEEL_STAIRS;
	public static final DeferredBlock<Block> BLACK_STEEL_SLAB;
	public static final DeferredBlock<Block> BLACK_STEEL_TRAPDOOR;
	public static final DeferredBlock<Block> BLACK_STEEL_WALL;
	public static final DeferredBlock<Block> STEEL_GIRDER;
	public static final DeferredBlock<Block> RED_STEEL_PLATING;
	public static final DeferredBlock<Block> RED_STEEL_STAIRS;
	public static final DeferredBlock<Block> RED_STEEL_SLAB;
	public static final DeferredBlock<Block> RED_STEEL_TRAPDOOR;
	public static final DeferredBlock<Block> RED_STEEL_WALL;
	public static final DeferredBlock<Block> BLACK_GUILDER_STEEL_TANK;
	public static final DeferredBlock<Block> BLACK_GUILDED_BOILER;
	public static final DeferredBlock<Block> RED_GUILDED_STEEL_TANK;
	public static final DeferredBlock<Block> RED_STEEL_TANK;
	public static final DeferredBlock<Block> RED_BOILER;
	public static final DeferredBlock<Block> RED_GUILDED_BOILER;
	public static final DeferredBlock<Block> GREEN_GILDED_STEEL_TANK;
	public static final DeferredBlock<Block> GREEN_STEEL_PLATING;
	public static final DeferredBlock<Block> GREEN_STEEL_SLAB;
	public static final DeferredBlock<Block> GREEN_STEEL_STAIRS;
	public static final DeferredBlock<Block> GREEN_STEEL_TANK;
	public static final DeferredBlock<Block> GREEN_STEEL_TRAPDOOR;
	public static final DeferredBlock<Block> GREEN_STEEL_WALL;
	public static final DeferredBlock<Block> GREEN_BOILER;
	public static final DeferredBlock<Block> GREEN_GILDED_BOILER;
	public static final DeferredBlock<Block> BROWN_GILDED_STEEL_TANK;
	public static final DeferredBlock<Block> BROWN_STEEL_PLATING;
	public static final DeferredBlock<Block> BROWN_STEEL_SLAB;
	public static final DeferredBlock<Block> BROWN_STEEL_STAIRS;
	public static final DeferredBlock<Block> BROWN_STEEL_TANK;
	public static final DeferredBlock<Block> BROWN_STEEL_TRAPDOOR;
	public static final DeferredBlock<Block> BROWN_STEEL_WALL;
	public static final DeferredBlock<Block> BROWN_BOILER;
	public static final DeferredBlock<Block> BROWN_GILDED_BOILER;
	public static final DeferredBlock<Block> BLUE_GILDED_STEEL_TANK;
	public static final DeferredBlock<Block> BLUE_STEEL_PLATING;
	public static final DeferredBlock<Block> BLUE_STEEL_SLAB;
	public static final DeferredBlock<Block> BLUE_STEEL_STAIRS;
	public static final DeferredBlock<Block> BLUE_STEEL_TANK;
	public static final DeferredBlock<Block> BLUE_STEEL_TRAPDOOR;
	public static final DeferredBlock<Block> BLUE_STEEL_WALL;
	public static final DeferredBlock<Block> BLUE_BOILER;
	public static final DeferredBlock<Block> BLUE_GILDED_BOILER;
	public static final DeferredBlock<Block> PURPLE_GILDED_STEEL_TANK;
	public static final DeferredBlock<Block> PURPLE_STEEL_PLATING;
	public static final DeferredBlock<Block> PURPLE_STEEL_SLAB;
	public static final DeferredBlock<Block> PURPLE_STEEL_STAIRS;
	public static final DeferredBlock<Block> PURPLE_STEEL_TANK;
	public static final DeferredBlock<Block> PURPLE_STEEL_TRAPDOOR;
	public static final DeferredBlock<Block> PURPLE_STEEL_WALL;
	public static final DeferredBlock<Block> CYAN_GILDED_STEEL_TANK;
	public static final DeferredBlock<Block> CYAN_STEEL_PLATING;
	public static final DeferredBlock<Block> CYAN_STEEL_SLAB;
	public static final DeferredBlock<Block> CYAN_STEEL_STAIRS;
	public static final DeferredBlock<Block> CYAN_STEEL_TANK;
	public static final DeferredBlock<Block> CYAN_STEEL_TRAPDOOR;
	public static final DeferredBlock<Block> CYAN_STEEL_WALL;
	public static final DeferredBlock<Block> PURPLE_BOILER;
	public static final DeferredBlock<Block> PURPLE_GILDED_BOILER;
	public static final DeferredBlock<Block> CYAN_BOILER;
	public static final DeferredBlock<Block> CYAN_GILDED_BOILER;
	public static final DeferredBlock<Block> LIGHT_GRAY_GILDED_STEEL_TANK;
	public static final DeferredBlock<Block> LIGHT_GRAY_STEEL_PLATING;
	public static final DeferredBlock<Block> LIGHT_GRAY_STEEL_SLAB;
	public static final DeferredBlock<Block> LIGHT_GRAY_STEEL_STAIRS;
	public static final DeferredBlock<Block> LIGHT_GRAY_STEEL_TANK;
	public static final DeferredBlock<Block> LIGHT_GRAY_STEEL_TRAPDOOR;
	public static final DeferredBlock<Block> LIGHT_GRAY_STEEL_WALL;
	public static final DeferredBlock<Block> LIGHT_GRAY_BOILER;
	public static final DeferredBlock<Block> LIGHT_GRAY_GILDED_BOILER;
	public static final DeferredBlock<Block> GRAY_GILDED_STEEL_TANK;
	public static final DeferredBlock<Block> GRAY_STEEL_PLATING;
	public static final DeferredBlock<Block> GRAY_STEEL_SLAB;
	public static final DeferredBlock<Block> GRAY_STEEL_STAIRS;
	public static final DeferredBlock<Block> GRAY_STEEL_TANK;
	public static final DeferredBlock<Block> GRAY_STEEL_TRAPDOOR;
	public static final DeferredBlock<Block> GRAY_STEEL_WALL;
	public static final DeferredBlock<Block> GRAY_BOILER;
	public static final DeferredBlock<Block> GRAY_GILDED_BOILER;
	public static final DeferredBlock<Block> PINK_GILDED_STEEL_TANK;
	public static final DeferredBlock<Block> PINK_STEEL_PLATING;
	public static final DeferredBlock<Block> PINK_STEEL_SLAB;
	public static final DeferredBlock<Block> PINK_STEEL_STAIRS;
	public static final DeferredBlock<Block> PINK_STEEL_TANK;
	public static final DeferredBlock<Block> PINK_STEEL_TRAPDOOR;
	public static final DeferredBlock<Block> PINK_STEEL_WALL;
	public static final DeferredBlock<Block> LIME_GILDED_STEEL_TANK;
	public static final DeferredBlock<Block> LIME_STEEL_PLATING;
	public static final DeferredBlock<Block> LIME_STEEL_SLAB;
	public static final DeferredBlock<Block> LIME_STEEL_STAIRS;
	public static final DeferredBlock<Block> LIME_STEEL_TANK;
	public static final DeferredBlock<Block> LIME_STEEL_TRAPDOOR;
	public static final DeferredBlock<Block> LIME_STEEL_WALL;
	public static final DeferredBlock<Block> PINK_BOILER;
	public static final DeferredBlock<Block> PINK_GILDED_BOILER;
	public static final DeferredBlock<Block> LIME_BOILER;
	public static final DeferredBlock<Block> LIME_GILDED_BOILER;
	public static final DeferredBlock<Block> YELLOW_GILDED_STEEL_TANK;
	public static final DeferredBlock<Block> YELLOW_STEEL_PLATING;
	public static final DeferredBlock<Block> YELLOW_STEEL_SLAB;
	public static final DeferredBlock<Block> YELLOW_STEEL_STAIRS;
	public static final DeferredBlock<Block> YELLOW_STEEL_TANK;
	public static final DeferredBlock<Block> YELLOW_STEEL_TRAPDOOR;
	public static final DeferredBlock<Block> YELLOW_STEEL_WALL;
	public static final DeferredBlock<Block> YELLOW_BOILER;
	public static final DeferredBlock<Block> YELLOW_GILDED_BOILER;
	public static final DeferredBlock<Block> LIGHT_BLUE_GILDED_STEEL_TANK;
	public static final DeferredBlock<Block> LIGHT_BLUE_STEEL_PLATING;
	public static final DeferredBlock<Block> LIGHT_BLUE_STEEL_SLAB;
	public static final DeferredBlock<Block> LIGHT_BLUE_STEEL_STAIRS;
	public static final DeferredBlock<Block> LIGHT_BLUE_STEEL_TANK;
	public static final DeferredBlock<Block> LIGHT_BLUE_STEEL_TRAPDOOR;
	public static final DeferredBlock<Block> LIGHT_BLUE_STEEL_WALL;
	public static final DeferredBlock<Block> MAGENTA_GILDED_STEEL_TANK;
	public static final DeferredBlock<Block> MAGENTA_STEEL_PLATING;
	public static final DeferredBlock<Block> MAGENTA_STEEL_SLAB;
	public static final DeferredBlock<Block> MAGENTA_STEEL_STAIRS;
	public static final DeferredBlock<Block> MAGENTA_STEEL_TANK;
	public static final DeferredBlock<Block> MAGENTA_STEEL_TRAPDOOR;
	public static final DeferredBlock<Block> MAGENTA_STEEL_WALL;
	public static final DeferredBlock<Block> MAGENTA_BOILER;
	public static final DeferredBlock<Block> MAGENTA_GILDED_BOILER;
	public static final DeferredBlock<Block> ORANGE_GILDED_STEEL_TANK;
	public static final DeferredBlock<Block> ORANGE_STEEL_PLATING;
	public static final DeferredBlock<Block> ORANGE_STEEL_SLAB;
	public static final DeferredBlock<Block> ORANGE_STEEL_STAIRS;
	public static final DeferredBlock<Block> ORANGE_STEEL_TANK;
	public static final DeferredBlock<Block> ORANGE_STEEL_TRAPDOOR;
	public static final DeferredBlock<Block> ORANGE_STEEL_WALL;
	public static final DeferredBlock<Block> ORANGE_BOILER;
	public static final DeferredBlock<Block> ORANGE_GILDED_BOILER;
	public static final DeferredBlock<Block> WHITE_GILDED_STEEL_TANK;
	public static final DeferredBlock<Block> WHITE_STEEL_PLATING;
	public static final DeferredBlock<Block> WHITE_STEEL_SLAB;
	public static final DeferredBlock<Block> WHITE_STEEL_STAIRS;
	public static final DeferredBlock<Block> WHITE_STEEL_TANK;
	public static final DeferredBlock<Block> WHITE_STEEL_TRAPDOOR;
	public static final DeferredBlock<Block> WHITE_STEEL_WALL;
	public static final DeferredBlock<Block> WHITE_BOILER;
	public static final DeferredBlock<Block> WHITE_GILDED_BOILER;
	public static final DeferredBlock<Block> LIGHT_BLUE_BOILER;
	public static final DeferredBlock<Block> LIGHT_BLUE_GILDED_BOILER;
	public static final DeferredBlock<Block> STRIPEDBLOCK_MIDDLE;
	public static final DeferredBlock<Block> COMPUTER_TERMINAL_STEEL;
	public static final DeferredBlock<Block> ROCKY_DIRT_SLAB;
	public static final DeferredBlock<Block> DIRT_SLAB;
	public static final DeferredBlock<Block> GRAVEL_SLAB;
	public static final DeferredBlock<Block> BALLAST;
	public static final DeferredBlock<Block> BALLAST_SLAB;
	public static final DeferredBlock<Block> SKELETON_5;
	public static final DeferredBlock<Block> SKELETON_6;
	public static final DeferredBlock<Block> ARROW_UP_SIGN;
	public static final DeferredBlock<Block> ARROW_RIGHT_SIGN;
	public static final DeferredBlock<Block> ARROW_LEFT_SIGN;
	public static final DeferredBlock<Block> ARROW_DOWN_SIGN;
	public static final DeferredBlock<Block> ARROW_RETURN_SIGN;
	public static final DeferredBlock<Block> NO_ENTRY_SIGN;
	public static final DeferredBlock<Block> ALARM_SIGN;
	public static final DeferredBlock<Block> ONEWAY_SIGN;
	public static final DeferredBlock<Block> STEEL_BLOCK;
	public static final DeferredBlock<Block> STEEL_MESH_TRAPDOOR;
	public static final DeferredBlock<Block> COPPER_BOILER;
	public static final DeferredBlock<Block> BRASS_BOILER;
	public static final DeferredBlock<Block> ZINC_BOILER;
	public static final DeferredBlock<Block> GAUGE_OUTER;
	public static final DeferredBlock<Block> GAUGE_INNER;
	public static final DeferredBlock<Block> COW_CATCHER_WHITE;
	public static final DeferredBlock<Block> COW_CATCHER_LIGHT_GRAY;
	public static final DeferredBlock<Block> COW_CATCHER_GRAY;
	public static final DeferredBlock<Block> COW_CATCHER_BLACK;
	public static final DeferredBlock<Block> COW_CATCHER_BROWN;
	public static final DeferredBlock<Block> COW_CATCHER_RED;
	public static final DeferredBlock<Block> COW_CATCHER_ORANGE;
	public static final DeferredBlock<Block> COW_CATCHER_YELLOW;
	public static final DeferredBlock<Block> COW_CATCHER_LIME;
	public static final DeferredBlock<Block> COW_CATCHER_GREEN;
	public static final DeferredBlock<Block> COW_CATCHER_CYAN;
	public static final DeferredBlock<Block> COW_CATCHER_LIGHT_BLUE;
	public static final DeferredBlock<Block> COW_CATCHER_BLUE;
	public static final DeferredBlock<Block> COW_CATCHER_PURPLE;
	public static final DeferredBlock<Block> COW_CATCHER_MAGENTA;
	public static final DeferredBlock<Block> COW_CATCHER_PINK;
	public static final DeferredBlock<Block> MAGENTA_SCREEN;
	public static final DeferredBlock<Block> ULTRA_WHITE;
	public static final DeferredBlock<Block> STARS;
	public static final DeferredBlock<Block> THOMAS_FACE;
	public static final DeferredBlock<Block> BEE_NEST_PASSIVE_GENERATOR;
	public static final DeferredBlock<Block> CAMPFIRE_PASSIVE_GENERATOR;
	public static final DeferredBlock<Block> FIRE_CHARGE_PASSIVE_GENERATOR;
	public static final DeferredBlock<Block> FIREWORK_PASSIVE_GENERATOR;
	public static final DeferredBlock<Block> FLINT_AND_STEEL_PASSIVE_GENERATOR;
	public static final DeferredBlock<Block> LAVA_BUCKET_PASSIVE_GENERATOR;
	public static final DeferredBlock<Block> SMALL_SMOKE_PASSIVE_GENERATOR;
	public static final DeferredBlock<Block> STEAM_PASSIVE_GENERATOR;
	public static final DeferredBlock<Block> TNT_PASSIVE_GENERATOR;
	public static final DeferredBlock<Block> WATER_BUCKET_PASSIVE_GENERATOR;
	public static final DeferredBlock<Block> ENGINE_PISTON;
	public static final DeferredBlock<Block> HELMS;
	public static final DeferredBlock<Block> LIGHT_GRAY_SCREEN;
	public static final DeferredBlock<Block> GRAY_SCREEN;
	public static final DeferredBlock<Block> BROWN_SCREEN;
	public static final DeferredBlock<Block> RED_SCREEN;
	public static final DeferredBlock<Block> ORANGE_SCREEN;
	public static final DeferredBlock<Block> YELLOW_SCREEN;
	public static final DeferredBlock<Block> DARK_GREEN_SCREEN;
	public static final DeferredBlock<Block> CYAN_SCREEN;
	public static final DeferredBlock<Block> LIGHT_BLUE_SCREEN;
	public static final DeferredBlock<Block> PURPLE_SCREEN;
	public static final DeferredBlock<Block> PINK_SCREEN;
	public static final DeferredBlock<Block> WHITE_BUFFER;
	public static final DeferredBlock<Block> LIGHT_GRAY_BUFFER;
	public static final DeferredBlock<Block> GRAY_BUFFER;
	public static final DeferredBlock<Block> BLACK_BUFFER;
	public static final DeferredBlock<Block> BROWN_BUFFER;
	public static final DeferredBlock<Block> RED_BUFFER;
	public static final DeferredBlock<Block> ORANGE_BUFFER;
	public static final DeferredBlock<Block> YELLOW_BUFFER;
	public static final DeferredBlock<Block> LIME_BUFFER;
	public static final DeferredBlock<Block> GREEN_BUFFER;
	public static final DeferredBlock<Block> CYAN_BUFFER;
	public static final DeferredBlock<Block> LIGHT_BLUE_BUFFER;
	public static final DeferredBlock<Block> BLUE_BUFFER;
	public static final DeferredBlock<Block> PURPLE_BUFFER;
	public static final DeferredBlock<Block> MAGENTA_BUFFER;
	public static final DeferredBlock<Block> PINK_BUFFER;
	public static final DeferredBlock<Block> GRANITE_BOILER;
	public static final DeferredBlock<Block> DIORITE_BOILER;
	public static final DeferredBlock<Block> RGB_STEEL_PLATING;
	public static final DeferredBlock<Block> RGB_STEEL_TANK;
	public static final DeferredBlock<Block> RGB_STEEL_SLAB;
	public static final DeferredBlock<Block> RGB_STEEL_STAIRS;
	public static final DeferredBlock<Block> RGB_STEEL_TRAPDOOR;
	public static final DeferredBlock<Block> RGB_STEEL_WALL;
	public static final DeferredBlock<Block> RGB_BOILER;
	public static final DeferredBlock<Block> VENT_T;
	public static final DeferredBlock<Block> VENT_T_UP;
	public static final DeferredBlock<Block> LABORATORY_LEFT_ARROW_RED;
	public static final DeferredBlock<Block> LABORATORY_RIGHT_ARROW_RED;
	public static final DeferredBlock<Block> LABORATORY_ROMAN_1_RED;
	public static final DeferredBlock<Block> LABORATORY_ROMAN_10_RED;
	public static final DeferredBlock<Block> LABORATORY_ROMAN_5_RED;
	public static final DeferredBlock<Block> LABORATORY_STRIPE_RED;
	public static final DeferredBlock<Block> LABORATORY_LEFT_ARROW_LIME;
	public static final DeferredBlock<Block> LABORATORY_RIGHT_ARROW_LIME;
	public static final DeferredBlock<Block> LABORATORY_ROMAN_10_LIME;
	public static final DeferredBlock<Block> LABORATORY_ROMAN_1_LIME;
	public static final DeferredBlock<Block> LABORATORY_ROMAN_5_LIME;
	public static final DeferredBlock<Block> LABORATORY_STRIPE_LIME;
	public static final DeferredBlock<Block> RGB_BUFFER;
	public static final DeferredBlock<Block> COW_CATCHER_RGB;
	public static final DeferredBlock<Block> ANIMATED_SERVER_RACK;
	public static final DeferredBlock<Block> WHITE_FUNNEL;
	public static final DeferredBlock<Block> LIGHT_GRAY_FUNNEL;
	public static final DeferredBlock<Block> GRAY_FUNNEL;
	public static final DeferredBlock<Block> BLACK_FUNNEL;
	public static final DeferredBlock<Block> BROWN_FUNNEL;
	public static final DeferredBlock<Block> RED_FUNNEL;
	public static final DeferredBlock<Block> ORANGE_FUNNEL;
	public static final DeferredBlock<Block> YELLOW_FUNNEL;
	public static final DeferredBlock<Block> LIME_FUNNEL;
	public static final DeferredBlock<Block> GREEN_FUNNEL;
	public static final DeferredBlock<Block> CYAN_FUNNEL;
	public static final DeferredBlock<Block> LIGHT_BLUE_FUNNEL;
	public static final DeferredBlock<Block> BLUE_FUNNEL;
	public static final DeferredBlock<Block> PURPLE_FUNNEL;
	public static final DeferredBlock<Block> MAGENTA_FUNNEL;
	public static final DeferredBlock<Block> PINK_FUNNEL;
	public static final DeferredBlock<Block> RGB_FUNNEL;
	public static final DeferredBlock<Block> SMOKE_STACK_OPENING;
	static {
		LIGHTON = REGISTRY.register("lighton", LightonBlock::new);
		LIGHTOFF = REGISTRY.register("lightoff", LightoffBlock::new);
		ALARM_LIGHTOFF = REGISTRY.register("alarm_lightoff", AlarmLightoffBlock::new);
		ALARM_LIGHTON = REGISTRY.register("alarm_lighton", AlarmLightonBlock::new);
		GREEN_LIGHT_ON = REGISTRY.register("green_light_on", GreenLightOnBlock::new);
		GREEN_LIGHT_OFF = REGISTRY.register("green_light_off", GreenLightOffBlock::new);
		BLUE_LIGHT_OFF = REGISTRY.register("blue_light_off", BlueLightOffBlock::new);
		BLUE_LIGHT_ON = REGISTRY.register("blue_light_on", BlueLightOnBlock::new);
		SOUND_GENERATOR = REGISTRY.register("sound_generator", SoundGeneratorBlock::new);
		PARTICLE_GENERATOR = REGISTRY.register("particle_generator", ParticleGeneratorBlock::new);
		STRIPEDBLOCK = REGISTRY.register("stripedblock", StripedblockBlock::new);
		ALARM_BLOCK = REGISTRY.register("alarm_block", AlarmBlockBlock::new);
		RADIATION_BLOCK = REGISTRY.register("radiation_block", RadiationBlockBlock::new);
		BIOHAZARD_BLOCK = REGISTRY.register("biohazard_block", BiohazardBlockBlock::new);
		DEATH_BLOCK = REGISTRY.register("death_block", DeathBlockBlock::new);
		ELECTRICITY_BLOCK = REGISTRY.register("electricity_block", ElectricityBlockBlock::new);
		CROSS_BLOCK = REGISTRY.register("cross_block", CrossBlockBlock::new);
		STRIPPEDBLOCK_HORIZONTAL = REGISTRY.register("strippedblock_horizontal", StrippedblockHorizontalBlock::new);
		STEEL_PLATING = REGISTRY.register("steel_plating", SteelPlatingBlock::new);
		STEEL_TILES = REGISTRY.register("steel_tiles", SteelTilesBlock::new);
		STEEL_PILLAR = REGISTRY.register("steel_pillar", SteelPillarBlock::new);
		STEEL_SEEMLESS = REGISTRY.register("steel_seemless", SteelSeemlessBlock::new);
		STEEL_DOOR = REGISTRY.register("steel_door", SteelDoorBlock::new);
		STEEL_TRAPDOOR = REGISTRY.register("steel_trapdoor", SteelTrapdoorBlock::new);
		STEEL_STAIRS = REGISTRY.register("steel_stairs", SteelStairsBlock::new);
		STEEL_SLAB = REGISTRY.register("steel_slab", SteelSlabBlock::new);
		STEEL_WALL = REGISTRY.register("steel_wall", SteelWallBlock::new);
		VENT_STRAIGHT = REGISTRY.register("vent_straight", VentStraightBlock::new);
		VENT_L = REGISTRY.register("vent_l", VentLBlock::new);
		VENT_L_UP = REGISTRY.register("vent_l_up", VentLUpBlock::new);
		PC_SETUP = REGISTRY.register("pc_setup", PcSetupBlock::new);
		COMPUTER_TERMINAL = REGISTRY.register("computer_terminal", ComputerTerminalBlock::new);
		SERVER_RACK = REGISTRY.register("server_rack", ServerRackBlock::new);
		EXIT_SIGN = REGISTRY.register("exit_sign", ExitSignBlock::new);
		BLACK_QUILTED_WOOL = REGISTRY.register("black_quilted_wool", BlackQuiltedWoolBlock::new);
		SOFT_AIR = REGISTRY.register("soft_air", SoftAirBlock::new);
		LABORATORY_BLOCK = REGISTRY.register("laboratory_block", LaboratoryBlockBlock::new);
		LABORATORY_VENT = REGISTRY.register("laboratory_vent", LaboratoryVentBlock::new);
		LABORATORY_PANEL = REGISTRY.register("laboratory_panel", LaboratoryPanelBlock::new);
		LABORATORY_STRIPE = REGISTRY.register("laboratory_stripe", LaboratoryStripeBlock::new);
		COPPER_COIL = REGISTRY.register("copper_coil", CopperCoilBlock::new);
		ISOLINEAR_FRONT_BLUE = REGISTRY.register("isolinear_front_blue", IsolinearFrontBlueBlock::new);
		ISOLINEAR_MIDDLE_BLUE = REGISTRY.register("isolinear_middle_blue", IsolinearMiddleBlueBlock::new);
		ISOLINEAR_BACK_BLUE = REGISTRY.register("isolinear_back_blue", IsolinearBackBlueBlock::new);
		CUT_LABORATORY_BLOCK = REGISTRY.register("cut_laboratory_block", CutLaboratoryBlockBlock::new);
		VOCALS_GENERATOR = REGISTRY.register("vocals_generator", VocalsGeneratorBlock::new);
		REINFORCED_GLASS = REGISTRY.register("reinforced_glass", ReinforcedGlassBlock::new);
		LABORATORY_ROMAN_1 = REGISTRY.register("laboratory_roman_1", LaboratoryRoman1Block::new);
		LABORATORY_ROMAN_5 = REGISTRY.register("laboratory_roman_5", LaboratoryRoman5Block::new);
		LABORATORY_ROMAN_10 = REGISTRY.register("laboratory_roman_10", LaboratoryRoman10Block::new);
		ISOLINEAR_BACK_RED = REGISTRY.register("isolinear_back_red", IsolinearBackRedBlock::new);
		ISOLINEAR_BACK_GREEN = REGISTRY.register("isolinear_back_green", IsolinearBackGreenBlock::new);
		ISOLINEAR_FRONT_GREEN = REGISTRY.register("isolinear_front_green", IsolinearFrontGreenBlock::new);
		ISOLINEAR_FRONT_RED = REGISTRY.register("isolinear_front_red", IsolinearFrontRedBlock::new);
		ISOLINEAR_MIDDLE_RED = REGISTRY.register("isolinear_middle_red", IsolinearMiddleRedBlock::new);
		ISOLINEAR_MIDDLE_GREEN = REGISTRY.register("isolinear_middle_green", IsolinearMiddleGreenBlock::new);
		ONEWAY_STONE = REGISTRY.register("oneway_stone", OnewayStoneBlock::new);
		VANTA_BLACK = REGISTRY.register("vanta_black", VantaBlackBlock::new);
		GREEN_SCREEN = REGISTRY.register("green_screen", GreenScreenBlock::new);
		BLUE_SCREEN = REGISTRY.register("blue_screen", BlueScreenBlock::new);
		ONEWAY_LABORATORY_BLOCK = REGISTRY.register("oneway_laboratory_block", OnewayLaboratoryBlockBlock::new);
		RUBBER_DUCK = REGISTRY.register("rubber_duck", RubberDuckBlock::new);
		FULL_LOG_PILE = REGISTRY.register("full_log_pile", FullLogPileBlock::new);
		LOG_PILE_1_TOP = REGISTRY.register("log_pile_1_top", LogPile1TopBlock::new);
		LOG_PILE_2_BOTTOM = REGISTRY.register("log_pile_2_bottom", LogPile2BottomBlock::new);
		LOG_PILE_2_TOP = REGISTRY.register("log_pile_2_top", LogPile2TopBlock::new);
		LOG_PILE_1_BOTTOM = REGISTRY.register("log_pile_1_bottom", LogPile1BottomBlock::new);
		LOG_PALISADE = REGISTRY.register("log_palisade", LogPalisadeBlock::new);
		BOOK_1 = REGISTRY.register("book_1", Book1Block::new);
		BOOK_2 = REGISTRY.register("book_2", Book2Block::new);
		SKELETON_1 = REGISTRY.register("skeleton_1", Skeleton1Block::new);
		SKELETON_2 = REGISTRY.register("skeleton_2", Skeleton2Block::new);
		SKELETON_3 = REGISTRY.register("skeleton_3", Skeleton3Block::new);
		SKELETON_4 = REGISTRY.register("skeleton_4", Skeleton4Block::new);
		YELLOW_ARROW_LEFT = REGISTRY.register("yellow_arrow_left", YellowArrowLeftBlock::new);
		YELLOW_ARROW_RIGHT = REGISTRY.register("yellow_arrow_right", YellowArrowRightBlock::new);
		LABORATORY_LEFT_ARROW = REGISTRY.register("laboratory_left_arrow", LaboratoryLeftArrowBlock::new);
		LABORATORY_RIGHT_ARROW = REGISTRY.register("laboratory_right_arrow", LaboratoryRightArrowBlock::new);
		LOG_PILE_CHAIR = REGISTRY.register("log_pile_chair", LogPileChairBlock::new);
		BLUE_QUILTED_WOOL = REGISTRY.register("blue_quilted_wool", BlueQuiltedWoolBlock::new);
		BROWN_QUILTED_WOOL = REGISTRY.register("brown_quilted_wool", BrownQuiltedWoolBlock::new);
		CYAN_QUILTED_WOOL = REGISTRY.register("cyan_quilted_wool", CyanQuiltedWoolBlock::new);
		GRAY_QUILTED_WOOL = REGISTRY.register("gray_quilted_wool", GrayQuiltedWoolBlock::new);
		GREEN_QUILTED_WOOL = REGISTRY.register("green_quilted_wool", GreenQuiltedWoolBlock::new);
		LIGHT_BLUE_QUILTED_WOOL = REGISTRY.register("light_blue_quilted_wool", LightBlueQuiltedWoolBlock::new);
		LIGHT_GRAY_QUILTED_WOOL = REGISTRY.register("light_gray_quilted_wool", LightGrayQuiltedWoolBlock::new);
		LIME_QUILTED_WOOL = REGISTRY.register("lime_quilted_wool", LimeQuiltedWoolBlock::new);
		MAGENTA_QUILTED_WOOL = REGISTRY.register("magenta_quilted_wool", MagentaQuiltedWoolBlock::new);
		ORANGE_QUILTED_WOOL = REGISTRY.register("orange_quilted_wool", OrangeQuiltedWoolBlock::new);
		PINK_QUILTED_WOOL = REGISTRY.register("pink_quilted_wool", PinkQuiltedWoolBlock::new);
		PURPLE_QUILTED_WOOL = REGISTRY.register("purple_quilted_wool", PurpleQuiltedWoolBlock::new);
		RED_QUILTED_WOOL = REGISTRY.register("red_quilted_wool", RedQuiltedWoolBlock::new);
		WHITE_QUILTED_WOOL = REGISTRY.register("white_quilted_wool", WhiteQuiltedWoolBlock::new);
		YELLOW_QUILTED_WOOL = REGISTRY.register("yellow_quilted_wool", YellowQuiltedWoolBlock::new);
		BLACK_CHAIR = REGISTRY.register("black_chair", BlackChairBlock::new);
		BLUE_CHAIR = REGISTRY.register("blue_chair", BlueChairBlock::new);
		BROWN_CHAIR = REGISTRY.register("brown_chair", BrownChairBlock::new);
		CYAN_CHAIR = REGISTRY.register("cyan_chair", CyanChairBlock::new);
		GRAY_CHAIR = REGISTRY.register("gray_chair", GrayChairBlock::new);
		GREEN_CHAIR = REGISTRY.register("green_chair", GreenChairBlock::new);
		LIGHT_BLUE_CHAIR = REGISTRY.register("light_blue_chair", LightBlueChairBlock::new);
		LIGHT_GRAY_CHAIR = REGISTRY.register("light_gray_chair", LightGrayChairBlock::new);
		LIME_CHAIR = REGISTRY.register("lime_chair", LimeChairBlock::new);
		MAGENTA_CHAIR = REGISTRY.register("magenta_chair", MagentaChairBlock::new);
		ORANGE_CHAIR = REGISTRY.register("orange_chair", OrangeChairBlock::new);
		PINK_CHAIR = REGISTRY.register("pink_chair", PinkChairBlock::new);
		PURPLE_CHAIR = REGISTRY.register("purple_chair", PurpleChairBlock::new);
		RED_CHAIR = REGISTRY.register("red_chair", RedChairBlock::new);
		WHITE_CHAIR = REGISTRY.register("white_chair", WhiteChairBlock::new);
		YELLOW_CHAIR = REGISTRY.register("yellow_chair", YellowChairBlock::new);
		HALF_LUMBER_DIAGONAL_LEFT = REGISTRY.register("half_lumber_diagonal_left", HalfLumberDiagonalLeftBlock::new);
		HALF_LUMBER_DIAGONAL_RIGHT = REGISTRY.register("half_lumber_diagonal_right", HalfLumberDiagonalRightBlock::new);
		HALF_LUMBER_VERTICAL = REGISTRY.register("half_lumber_vertical", HalfLumberVerticalBlock::new);
		HALF_LUMBER_HORIZONTAL = REGISTRY.register("half_lumber_horizontal", HalfLumberHorizontalBlock::new);
		HALF_LUMBER_BORDER = REGISTRY.register("half_lumber_border", HalfLumberBorderBlock::new);
		HALF_LUMBER_BRICK_BORDER = REGISTRY.register("half_lumber_brick_border", HalfLumberBrickBorderBlock::new);
		HALF_LUMBER_BRICK_DIAGONAL_LEFT = REGISTRY.register("half_lumber_brick_diagonal_left", HalfLumberBrickDiagonalLeftBlock::new);
		HALF_LUMBER_BRICK_DIAGONAL_RIGHT = REGISTRY.register("half_lumber_brick_diagonal_right", HalfLumberBrickDiagonalRightBlock::new);
		HALF_LUMBER_BRICK_HORIZONTAL = REGISTRY.register("half_lumber_brick_horizontal", HalfLumberBrickHorizontalBlock::new);
		HALF_LUMBER_BRICK_VERTICAL = REGISTRY.register("half_lumber_brick_vertical", HalfLumberBrickVerticalBlock::new);
		ROCKY_DIRT = REGISTRY.register("rocky_dirt", RockyDirtBlock::new);
		STEEL_FRAME = REGISTRY.register("steel_frame", SteelFrameBlock::new);
		POLISHED_STEEL_PLATING = REGISTRY.register("polished_steel_plating", PolishedSteelPlatingBlock::new);
		TUNGSTEN_CARBITE = REGISTRY.register("tungsten_carbite", TungstenCarbiteBlock::new);
		STEEL_COLOUMN = REGISTRY.register("steel_coloumn", SteelColoumnBlock::new);
		TRACK_END = REGISTRY.register("track_end", TrackEndBlock::new);
		CREATE_BOILER = REGISTRY.register("create_boiler", CreateBoilerBlock::new);
		BLACK_BOILER = REGISTRY.register("black_boiler", BlackBoilerBlock::new);
		BLACK_STEEL_TANK = REGISTRY.register("black_steel_tank", BlackSteelTankBlock::new);
		BLACK_STEEL_PLATING = REGISTRY.register("black_steel_plating", BlackSteelPlatingBlock::new);
		BLACK_STEEL_STAIRS = REGISTRY.register("black_steel_stairs", BlackSteelStairsBlock::new);
		BLACK_STEEL_SLAB = REGISTRY.register("black_steel_slab", BlackSteelSlabBlock::new);
		BLACK_STEEL_TRAPDOOR = REGISTRY.register("black_steel_trapdoor", BlackSteelTrapdoorBlock::new);
		BLACK_STEEL_WALL = REGISTRY.register("black_steel_wall", BlackSteelWallBlock::new);
		STEEL_GIRDER = REGISTRY.register("steel_girder", SteelGirderBlock::new);
		RED_STEEL_PLATING = REGISTRY.register("red_steel_plating", RedSteelPlatingBlock::new);
		RED_STEEL_STAIRS = REGISTRY.register("red_steel_stairs", RedSteelStairsBlock::new);
		RED_STEEL_SLAB = REGISTRY.register("red_steel_slab", RedSteelSlabBlock::new);
		RED_STEEL_TRAPDOOR = REGISTRY.register("red_steel_trapdoor", RedSteelTrapdoorBlock::new);
		RED_STEEL_WALL = REGISTRY.register("red_steel_wall", RedSteelWallBlock::new);
		BLACK_GUILDER_STEEL_TANK = REGISTRY.register("black_guilder_steel_tank", BlackGuilderSteelTankBlock::new);
		BLACK_GUILDED_BOILER = REGISTRY.register("black_guilded_boiler", BlackGuildedBoilerBlock::new);
		RED_GUILDED_STEEL_TANK = REGISTRY.register("red_guilded_steel_tank", RedGuildedSteelTankBlock::new);
		RED_STEEL_TANK = REGISTRY.register("red_steel_tank", RedSteelTankBlock::new);
		RED_BOILER = REGISTRY.register("red_boiler", RedBoilerBlock::new);
		RED_GUILDED_BOILER = REGISTRY.register("red_guilded_boiler", RedGuildedBoilerBlock::new);
		GREEN_GILDED_STEEL_TANK = REGISTRY.register("green_gilded_steel_tank", GreenGildedSteelTankBlock::new);
		GREEN_STEEL_PLATING = REGISTRY.register("green_steel_plating", GreenSteelPlatingBlock::new);
		GREEN_STEEL_SLAB = REGISTRY.register("green_steel_slab", GreenSteelSlabBlock::new);
		GREEN_STEEL_STAIRS = REGISTRY.register("green_steel_stairs", GreenSteelStairsBlock::new);
		GREEN_STEEL_TANK = REGISTRY.register("green_steel_tank", GreenSteelTankBlock::new);
		GREEN_STEEL_TRAPDOOR = REGISTRY.register("green_steel_trapdoor", GreenSteelTrapdoorBlock::new);
		GREEN_STEEL_WALL = REGISTRY.register("green_steel_wall", GreenSteelWallBlock::new);
		GREEN_BOILER = REGISTRY.register("green_boiler", GreenBoilerBlock::new);
		GREEN_GILDED_BOILER = REGISTRY.register("green_gilded_boiler", GreenGildedBoilerBlock::new);
		BROWN_GILDED_STEEL_TANK = REGISTRY.register("brown_gilded_steel_tank", BrownGildedSteelTankBlock::new);
		BROWN_STEEL_PLATING = REGISTRY.register("brown_steel_plating", BrownSteelPlatingBlock::new);
		BROWN_STEEL_SLAB = REGISTRY.register("brown_steel_slab", BrownSteelSlabBlock::new);
		BROWN_STEEL_STAIRS = REGISTRY.register("brown_steel_stairs", BrownSteelStairsBlock::new);
		BROWN_STEEL_TANK = REGISTRY.register("brown_steel_tank", BrownSteelTankBlock::new);
		BROWN_STEEL_TRAPDOOR = REGISTRY.register("brown_steel_trapdoor", BrownSteelTrapdoorBlock::new);
		BROWN_STEEL_WALL = REGISTRY.register("brown_steel_wall", BrownSteelWallBlock::new);
		BROWN_BOILER = REGISTRY.register("brown_boiler", BrownBoilerBlock::new);
		BROWN_GILDED_BOILER = REGISTRY.register("brown_gilded_boiler", BrownGildedBoilerBlock::new);
		BLUE_GILDED_STEEL_TANK = REGISTRY.register("blue_gilded_steel_tank", BlueGildedSteelTankBlock::new);
		BLUE_STEEL_PLATING = REGISTRY.register("blue_steel_plating", BlueSteelPlatingBlock::new);
		BLUE_STEEL_SLAB = REGISTRY.register("blue_steel_slab", BlueSteelSlabBlock::new);
		BLUE_STEEL_STAIRS = REGISTRY.register("blue_steel_stairs", BlueSteelStairsBlock::new);
		BLUE_STEEL_TANK = REGISTRY.register("blue_steel_tank", BlueSteelTankBlock::new);
		BLUE_STEEL_TRAPDOOR = REGISTRY.register("blue_steel_trapdoor", BlueSteelTrapdoorBlock::new);
		BLUE_STEEL_WALL = REGISTRY.register("blue_steel_wall", BlueSteelWallBlock::new);
		BLUE_BOILER = REGISTRY.register("blue_boiler", BlueBoilerBlock::new);
		BLUE_GILDED_BOILER = REGISTRY.register("blue_gilded_boiler", BlueGildedBoilerBlock::new);
		PURPLE_GILDED_STEEL_TANK = REGISTRY.register("purple_gilded_steel_tank", PurpleGildedSteelTankBlock::new);
		PURPLE_STEEL_PLATING = REGISTRY.register("purple_steel_plating", PurpleSteelPlatingBlock::new);
		PURPLE_STEEL_SLAB = REGISTRY.register("purple_steel_slab", PurpleSteelSlabBlock::new);
		PURPLE_STEEL_STAIRS = REGISTRY.register("purple_steel_stairs", PurpleSteelStairsBlock::new);
		PURPLE_STEEL_TANK = REGISTRY.register("purple_steel_tank", PurpleSteelTankBlock::new);
		PURPLE_STEEL_TRAPDOOR = REGISTRY.register("purple_steel_trapdoor", PurpleSteelTrapdoorBlock::new);
		PURPLE_STEEL_WALL = REGISTRY.register("purple_steel_wall", PurpleSteelWallBlock::new);
		CYAN_GILDED_STEEL_TANK = REGISTRY.register("cyan_gilded_steel_tank", CyanGildedSteelTankBlock::new);
		CYAN_STEEL_PLATING = REGISTRY.register("cyan_steel_plating", CyanSteelPlatingBlock::new);
		CYAN_STEEL_SLAB = REGISTRY.register("cyan_steel_slab", CyanSteelSlabBlock::new);
		CYAN_STEEL_STAIRS = REGISTRY.register("cyan_steel_stairs", CyanSteelStairsBlock::new);
		CYAN_STEEL_TANK = REGISTRY.register("cyan_steel_tank", CyanSteelTankBlock::new);
		CYAN_STEEL_TRAPDOOR = REGISTRY.register("cyan_steel_trapdoor", CyanSteelTrapdoorBlock::new);
		CYAN_STEEL_WALL = REGISTRY.register("cyan_steel_wall", CyanSteelWallBlock::new);
		PURPLE_BOILER = REGISTRY.register("purple_boiler", PurpleBoilerBlock::new);
		PURPLE_GILDED_BOILER = REGISTRY.register("purple_gilded_boiler", PurpleGildedBoilerBlock::new);
		CYAN_BOILER = REGISTRY.register("cyan_boiler", CyanBoilerBlock::new);
		CYAN_GILDED_BOILER = REGISTRY.register("cyan_gilded_boiler", CyanGildedBoilerBlock::new);
		LIGHT_GRAY_GILDED_STEEL_TANK = REGISTRY.register("light_gray_gilded_steel_tank", LightGrayGildedSteelTankBlock::new);
		LIGHT_GRAY_STEEL_PLATING = REGISTRY.register("light_gray_steel_plating", LightGraySteelPlatingBlock::new);
		LIGHT_GRAY_STEEL_SLAB = REGISTRY.register("light_gray_steel_slab", LightGraySteelSlabBlock::new);
		LIGHT_GRAY_STEEL_STAIRS = REGISTRY.register("light_gray_steel_stairs", LightGraySteelStairsBlock::new);
		LIGHT_GRAY_STEEL_TANK = REGISTRY.register("light_gray_steel_tank", LightGraySteelTankBlock::new);
		LIGHT_GRAY_STEEL_TRAPDOOR = REGISTRY.register("light_gray_steel_trapdoor", LightGraySteelTrapdoorBlock::new);
		LIGHT_GRAY_STEEL_WALL = REGISTRY.register("light_gray_steel_wall", LightGraySteelWallBlock::new);
		LIGHT_GRAY_BOILER = REGISTRY.register("light_gray_boiler", LightGrayBoilerBlock::new);
		LIGHT_GRAY_GILDED_BOILER = REGISTRY.register("light_gray_gilded_boiler", LightGrayGildedBoilerBlock::new);
		GRAY_GILDED_STEEL_TANK = REGISTRY.register("gray_gilded_steel_tank", GrayGildedSteelTankBlock::new);
		GRAY_STEEL_PLATING = REGISTRY.register("gray_steel_plating", GraySteelPlatingBlock::new);
		GRAY_STEEL_SLAB = REGISTRY.register("gray_steel_slab", GraySteelSlabBlock::new);
		GRAY_STEEL_STAIRS = REGISTRY.register("gray_steel_stairs", GraySteelStairsBlock::new);
		GRAY_STEEL_TANK = REGISTRY.register("gray_steel_tank", GraySteelTankBlock::new);
		GRAY_STEEL_TRAPDOOR = REGISTRY.register("gray_steel_trapdoor", GraySteelTrapdoorBlock::new);
		GRAY_STEEL_WALL = REGISTRY.register("gray_steel_wall", GraySteelWallBlock::new);
		GRAY_BOILER = REGISTRY.register("gray_boiler", GrayBoilerBlock::new);
		GRAY_GILDED_BOILER = REGISTRY.register("gray_gilded_boiler", GrayGildedBoilerBlock::new);
		PINK_GILDED_STEEL_TANK = REGISTRY.register("pink_gilded_steel_tank", PinkGildedSteelTankBlock::new);
		PINK_STEEL_PLATING = REGISTRY.register("pink_steel_plating", PinkSteelPlatingBlock::new);
		PINK_STEEL_SLAB = REGISTRY.register("pink_steel_slab", PinkSteelSlabBlock::new);
		PINK_STEEL_STAIRS = REGISTRY.register("pink_steel_stairs", PinkSteelStairsBlock::new);
		PINK_STEEL_TANK = REGISTRY.register("pink_steel_tank", PinkSteelTankBlock::new);
		PINK_STEEL_TRAPDOOR = REGISTRY.register("pink_steel_trapdoor", PinkSteelTrapdoorBlock::new);
		PINK_STEEL_WALL = REGISTRY.register("pink_steel_wall", PinkSteelWallBlock::new);
		LIME_GILDED_STEEL_TANK = REGISTRY.register("lime_gilded_steel_tank", LimeGildedSteelTankBlock::new);
		LIME_STEEL_PLATING = REGISTRY.register("lime_steel_plating", LimeSteelPlatingBlock::new);
		LIME_STEEL_SLAB = REGISTRY.register("lime_steel_slab", LimeSteelSlabBlock::new);
		LIME_STEEL_STAIRS = REGISTRY.register("lime_steel_stairs", LimeSteelStairsBlock::new);
		LIME_STEEL_TANK = REGISTRY.register("lime_steel_tank", LimeSteelTankBlock::new);
		LIME_STEEL_TRAPDOOR = REGISTRY.register("lime_steel_trapdoor", LimeSteelTrapdoorBlock::new);
		LIME_STEEL_WALL = REGISTRY.register("lime_steel_wall", LimeSteelWallBlock::new);
		PINK_BOILER = REGISTRY.register("pink_boiler", PinkBoilerBlock::new);
		PINK_GILDED_BOILER = REGISTRY.register("pink_gilded_boiler", PinkGildedBoilerBlock::new);
		LIME_BOILER = REGISTRY.register("lime_boiler", LimeBoilerBlock::new);
		LIME_GILDED_BOILER = REGISTRY.register("lime_gilded_boiler", LimeGildedBoilerBlock::new);
		YELLOW_GILDED_STEEL_TANK = REGISTRY.register("yellow_gilded_steel_tank", YellowGildedSteelTankBlock::new);
		YELLOW_STEEL_PLATING = REGISTRY.register("yellow_steel_plating", YellowSteelPlatingBlock::new);
		YELLOW_STEEL_SLAB = REGISTRY.register("yellow_steel_slab", YellowSteelSlabBlock::new);
		YELLOW_STEEL_STAIRS = REGISTRY.register("yellow_steel_stairs", YellowSteelStairsBlock::new);
		YELLOW_STEEL_TANK = REGISTRY.register("yellow_steel_tank", YellowSteelTankBlock::new);
		YELLOW_STEEL_TRAPDOOR = REGISTRY.register("yellow_steel_trapdoor", YellowSteelTrapdoorBlock::new);
		YELLOW_STEEL_WALL = REGISTRY.register("yellow_steel_wall", YellowSteelWallBlock::new);
		YELLOW_BOILER = REGISTRY.register("yellow_boiler", YellowBoilerBlock::new);
		YELLOW_GILDED_BOILER = REGISTRY.register("yellow_gilded_boiler", YellowGildedBoilerBlock::new);
		LIGHT_BLUE_GILDED_STEEL_TANK = REGISTRY.register("light_blue_gilded_steel_tank", LightBlueGildedSteelTankBlock::new);
		LIGHT_BLUE_STEEL_PLATING = REGISTRY.register("light_blue_steel_plating", LightBlueSteelPlatingBlock::new);
		LIGHT_BLUE_STEEL_SLAB = REGISTRY.register("light_blue_steel_slab", LightBlueSteelSlabBlock::new);
		LIGHT_BLUE_STEEL_STAIRS = REGISTRY.register("light_blue_steel_stairs", LightBlueSteelStairsBlock::new);
		LIGHT_BLUE_STEEL_TANK = REGISTRY.register("light_blue_steel_tank", LightBlueSteelTankBlock::new);
		LIGHT_BLUE_STEEL_TRAPDOOR = REGISTRY.register("light_blue_steel_trapdoor", LightBlueSteelTrapdoorBlock::new);
		LIGHT_BLUE_STEEL_WALL = REGISTRY.register("light_blue_steel_wall", LightBlueSteelWallBlock::new);
		MAGENTA_GILDED_STEEL_TANK = REGISTRY.register("magenta_gilded_steel_tank", MagentaGildedSteelTankBlock::new);
		MAGENTA_STEEL_PLATING = REGISTRY.register("magenta_steel_plating", MagentaSteelPlatingBlock::new);
		MAGENTA_STEEL_SLAB = REGISTRY.register("magenta_steel_slab", MagentaSteelSlabBlock::new);
		MAGENTA_STEEL_STAIRS = REGISTRY.register("magenta_steel_stairs", MagentaSteelStairsBlock::new);
		MAGENTA_STEEL_TANK = REGISTRY.register("magenta_steel_tank", MagentaSteelTankBlock::new);
		MAGENTA_STEEL_TRAPDOOR = REGISTRY.register("magenta_steel_trapdoor", MagentaSteelTrapdoorBlock::new);
		MAGENTA_STEEL_WALL = REGISTRY.register("magenta_steel_wall", MagentaSteelWallBlock::new);
		MAGENTA_BOILER = REGISTRY.register("magenta_boiler", MagentaBoilerBlock::new);
		MAGENTA_GILDED_BOILER = REGISTRY.register("magenta_gilded_boiler", MagentaGildedBoilerBlock::new);
		ORANGE_GILDED_STEEL_TANK = REGISTRY.register("orange_gilded_steel_tank", OrangeGildedSteelTankBlock::new);
		ORANGE_STEEL_PLATING = REGISTRY.register("orange_steel_plating", OrangeSteelPlatingBlock::new);
		ORANGE_STEEL_SLAB = REGISTRY.register("orange_steel_slab", OrangeSteelSlabBlock::new);
		ORANGE_STEEL_STAIRS = REGISTRY.register("orange_steel_stairs", OrangeSteelStairsBlock::new);
		ORANGE_STEEL_TANK = REGISTRY.register("orange_steel_tank", OrangeSteelTankBlock::new);
		ORANGE_STEEL_TRAPDOOR = REGISTRY.register("orange_steel_trapdoor", OrangeSteelTrapdoorBlock::new);
		ORANGE_STEEL_WALL = REGISTRY.register("orange_steel_wall", OrangeSteelWallBlock::new);
		ORANGE_BOILER = REGISTRY.register("orange_boiler", OrangeBoilerBlock::new);
		ORANGE_GILDED_BOILER = REGISTRY.register("orange_gilded_boiler", OrangeGildedBoilerBlock::new);
		WHITE_GILDED_STEEL_TANK = REGISTRY.register("white_gilded_steel_tank", WhiteGildedSteelTankBlock::new);
		WHITE_STEEL_PLATING = REGISTRY.register("white_steel_plating", WhiteSteelPlatingBlock::new);
		WHITE_STEEL_SLAB = REGISTRY.register("white_steel_slab", WhiteSteelSlabBlock::new);
		WHITE_STEEL_STAIRS = REGISTRY.register("white_steel_stairs", WhiteSteelStairsBlock::new);
		WHITE_STEEL_TANK = REGISTRY.register("white_steel_tank", WhiteSteelTankBlock::new);
		WHITE_STEEL_TRAPDOOR = REGISTRY.register("white_steel_trapdoor", WhiteSteelTrapdoorBlock::new);
		WHITE_STEEL_WALL = REGISTRY.register("white_steel_wall", WhiteSteelWallBlock::new);
		WHITE_BOILER = REGISTRY.register("white_boiler", WhiteBoilerBlock::new);
		WHITE_GILDED_BOILER = REGISTRY.register("white_gilded_boiler", WhiteGildedBoilerBlock::new);
		LIGHT_BLUE_BOILER = REGISTRY.register("light_blue_boiler", LightBlueBoilerBlock::new);
		LIGHT_BLUE_GILDED_BOILER = REGISTRY.register("light_blue_gilded_boiler", LightBlueGildedBoilerBlock::new);
		STRIPEDBLOCK_MIDDLE = REGISTRY.register("stripedblock_middle", StripedblockMiddleBlock::new);
		COMPUTER_TERMINAL_STEEL = REGISTRY.register("computer_terminal_steel", ComputerTerminalSteelBlock::new);
		ROCKY_DIRT_SLAB = REGISTRY.register("rocky_dirt_slab", RockyDirtSlabBlock::new);
		DIRT_SLAB = REGISTRY.register("dirt_slab", DirtSlabBlock::new);
		GRAVEL_SLAB = REGISTRY.register("gravel_slab", GravelSlabBlock::new);
		BALLAST = REGISTRY.register("ballast", BallastBlock::new);
		BALLAST_SLAB = REGISTRY.register("ballast_slab", BallastSlabBlock::new);
		SKELETON_5 = REGISTRY.register("skeleton_5", Skeleton5Block::new);
		SKELETON_6 = REGISTRY.register("skeleton_6", Skeleton6Block::new);
		ARROW_UP_SIGN = REGISTRY.register("arrow_up_sign", ArrowUpSignBlock::new);
		ARROW_RIGHT_SIGN = REGISTRY.register("arrow_right_sign", ArrowRightSignBlock::new);
		ARROW_LEFT_SIGN = REGISTRY.register("arrow_left_sign", ArrowLeftSignBlock::new);
		ARROW_DOWN_SIGN = REGISTRY.register("arrow_down_sign", ArrowDownSignBlock::new);
		ARROW_RETURN_SIGN = REGISTRY.register("arrow_return_sign", ArrowReturnSignBlock::new);
		NO_ENTRY_SIGN = REGISTRY.register("no_entry_sign", NoEntrySignBlock::new);
		ALARM_SIGN = REGISTRY.register("alarm_sign", AlarmSignBlock::new);
		ONEWAY_SIGN = REGISTRY.register("oneway_sign", OnewaySignBlock::new);
		STEEL_BLOCK = REGISTRY.register("steel_block", SteelBlockBlock::new);
		STEEL_MESH_TRAPDOOR = REGISTRY.register("steel_mesh_trapdoor", SteelMeshTrapdoorBlock::new);
		COPPER_BOILER = REGISTRY.register("copper_boiler", CopperBoilerBlock::new);
		BRASS_BOILER = REGISTRY.register("brass_boiler", BrassBoilerBlock::new);
		ZINC_BOILER = REGISTRY.register("zinc_boiler", ZincBoilerBlock::new);
		GAUGE_OUTER = REGISTRY.register("gauge_outer", GaugeOuterBlock::new);
		GAUGE_INNER = REGISTRY.register("gauge_inner", GaugeInnerBlock::new);
		COW_CATCHER_WHITE = REGISTRY.register("cow_catcher_white", CowCatcherWhiteBlock::new);
		COW_CATCHER_LIGHT_GRAY = REGISTRY.register("cow_catcher_light_gray", CowCatcherLightGrayBlock::new);
		COW_CATCHER_GRAY = REGISTRY.register("cow_catcher_gray", CowCatcherGrayBlock::new);
		COW_CATCHER_BLACK = REGISTRY.register("cow_catcher_black", CowCatcherBlackBlock::new);
		COW_CATCHER_BROWN = REGISTRY.register("cow_catcher_brown", CowCatcherBrownBlock::new);
		COW_CATCHER_RED = REGISTRY.register("cow_catcher_red", CowCatcherRedBlock::new);
		COW_CATCHER_ORANGE = REGISTRY.register("cow_catcher_orange", CowCatcherOrangeBlock::new);
		COW_CATCHER_YELLOW = REGISTRY.register("cow_catcher_yellow", CowCatcherYellowBlock::new);
		COW_CATCHER_LIME = REGISTRY.register("cow_catcher_lime", CowCatcherLimeBlock::new);
		COW_CATCHER_GREEN = REGISTRY.register("cow_catcher_green", CowCatcherGreenBlock::new);
		COW_CATCHER_CYAN = REGISTRY.register("cow_catcher_cyan", CowCatcherCyanBlock::new);
		COW_CATCHER_LIGHT_BLUE = REGISTRY.register("cow_catcher_light_blue", CowCatcherLightBlueBlock::new);
		COW_CATCHER_BLUE = REGISTRY.register("cow_catcher_blue", CowCatcherBlueBlock::new);
		COW_CATCHER_PURPLE = REGISTRY.register("cow_catcher_purple", CowCatcherPurpleBlock::new);
		COW_CATCHER_MAGENTA = REGISTRY.register("cow_catcher_magenta", CowCatcherMagentaBlock::new);
		COW_CATCHER_PINK = REGISTRY.register("cow_catcher_pink", CowCatcherPinkBlock::new);
		MAGENTA_SCREEN = REGISTRY.register("magenta_screen", MagentaScreenBlock::new);
		ULTRA_WHITE = REGISTRY.register("ultra_white", UltraWhiteBlock::new);
		STARS = REGISTRY.register("stars", StarsBlock::new);
		THOMAS_FACE = REGISTRY.register("thomas_face", ThomasFaceBlock::new);
		BEE_NEST_PASSIVE_GENERATOR = REGISTRY.register("bee_nest_passive_generator", BeeNestPassiveGeneratorBlock::new);
		CAMPFIRE_PASSIVE_GENERATOR = REGISTRY.register("campfire_passive_generator", CampfirePassiveGeneratorBlock::new);
		FIRE_CHARGE_PASSIVE_GENERATOR = REGISTRY.register("fire_charge_passive_generator", FireChargePassiveGeneratorBlock::new);
		FIREWORK_PASSIVE_GENERATOR = REGISTRY.register("firework_passive_generator", FireworkPassiveGeneratorBlock::new);
		FLINT_AND_STEEL_PASSIVE_GENERATOR = REGISTRY.register("flint_and_steel_passive_generator", FlintAndSteelPassiveGeneratorBlock::new);
		LAVA_BUCKET_PASSIVE_GENERATOR = REGISTRY.register("lava_bucket_passive_generator", LavaBucketPassiveGeneratorBlock::new);
		SMALL_SMOKE_PASSIVE_GENERATOR = REGISTRY.register("small_smoke_passive_generator", SmallSmokePassiveGeneratorBlock::new);
		STEAM_PASSIVE_GENERATOR = REGISTRY.register("steam_passive_generator", SteamPassiveGeneratorBlock::new);
		TNT_PASSIVE_GENERATOR = REGISTRY.register("tnt_passive_generator", TntPassiveGeneratorBlock::new);
		WATER_BUCKET_PASSIVE_GENERATOR = REGISTRY.register("water_bucket_passive_generator", WaterBucketPassiveGeneratorBlock::new);
		ENGINE_PISTON = REGISTRY.register("engine_piston", EnginePistonBlock::new);
		HELMS = REGISTRY.register("helms", HelmsBlock::new);
		LIGHT_GRAY_SCREEN = REGISTRY.register("light_gray_screen", LightGrayScreenBlock::new);
		GRAY_SCREEN = REGISTRY.register("gray_screen", GrayScreenBlock::new);
		BROWN_SCREEN = REGISTRY.register("brown_screen", BrownScreenBlock::new);
		RED_SCREEN = REGISTRY.register("red_screen", RedScreenBlock::new);
		ORANGE_SCREEN = REGISTRY.register("orange_screen", OrangeScreenBlock::new);
		YELLOW_SCREEN = REGISTRY.register("yellow_screen", YellowScreenBlock::new);
		DARK_GREEN_SCREEN = REGISTRY.register("dark_green_screen", DarkGreenScreenBlock::new);
		CYAN_SCREEN = REGISTRY.register("cyan_screen", CyanScreenBlock::new);
		LIGHT_BLUE_SCREEN = REGISTRY.register("light_blue_screen", LightBlueScreenBlock::new);
		PURPLE_SCREEN = REGISTRY.register("purple_screen", PurpleScreenBlock::new);
		PINK_SCREEN = REGISTRY.register("pink_screen", PinkScreenBlock::new);
		WHITE_BUFFER = REGISTRY.register("white_buffer", WhiteBufferBlock::new);
		LIGHT_GRAY_BUFFER = REGISTRY.register("light_gray_buffer", LightGrayBufferBlock::new);
		GRAY_BUFFER = REGISTRY.register("gray_buffer", GrayBufferBlock::new);
		BLACK_BUFFER = REGISTRY.register("black_buffer", BlackBufferBlock::new);
		BROWN_BUFFER = REGISTRY.register("brown_buffer", BrownBufferBlock::new);
		RED_BUFFER = REGISTRY.register("red_buffer", RedBufferBlock::new);
		ORANGE_BUFFER = REGISTRY.register("orange_buffer", OrangeBufferBlock::new);
		YELLOW_BUFFER = REGISTRY.register("yellow_buffer", YellowBufferBlock::new);
		LIME_BUFFER = REGISTRY.register("lime_buffer", LimeBufferBlock::new);
		GREEN_BUFFER = REGISTRY.register("green_buffer", GreenBufferBlock::new);
		CYAN_BUFFER = REGISTRY.register("cyan_buffer", CyanBufferBlock::new);
		LIGHT_BLUE_BUFFER = REGISTRY.register("light_blue_buffer", LightBlueBufferBlock::new);
		BLUE_BUFFER = REGISTRY.register("blue_buffer", BlueBufferBlock::new);
		PURPLE_BUFFER = REGISTRY.register("purple_buffer", PurpleBufferBlock::new);
		MAGENTA_BUFFER = REGISTRY.register("magenta_buffer", MagentaBufferBlock::new);
		PINK_BUFFER = REGISTRY.register("pink_buffer", PinkBufferBlock::new);
		GRANITE_BOILER = REGISTRY.register("granite_boiler", GraniteBoilerBlock::new);
		DIORITE_BOILER = REGISTRY.register("diorite_boiler", DioriteBoilerBlock::new);
		RGB_STEEL_PLATING = REGISTRY.register("rgb_steel_plating", RGBSteelPlatingBlock::new);
		RGB_STEEL_TANK = REGISTRY.register("rgb_steel_tank", RGBSteelTankBlock::new);
		RGB_STEEL_SLAB = REGISTRY.register("rgb_steel_slab", RGBSteelSlabBlock::new);
		RGB_STEEL_STAIRS = REGISTRY.register("rgb_steel_stairs", RGBSteelStairsBlock::new);
		RGB_STEEL_TRAPDOOR = REGISTRY.register("rgb_steel_trapdoor", RGBSteelTrapdoorBlock::new);
		RGB_STEEL_WALL = REGISTRY.register("rgb_steel_wall", RGBSteelWallBlock::new);
		RGB_BOILER = REGISTRY.register("rgb_boiler", RGBBoilerBlock::new);
		VENT_T = REGISTRY.register("vent_t", VentTBlock::new);
		VENT_T_UP = REGISTRY.register("vent_t_up", VentTUpBlock::new);
		LABORATORY_LEFT_ARROW_RED = REGISTRY.register("laboratory_left_arrow_red", LaboratoryLeftArrowRedBlock::new);
		LABORATORY_RIGHT_ARROW_RED = REGISTRY.register("laboratory_right_arrow_red", LaboratoryRightArrowRedBlock::new);
		LABORATORY_ROMAN_1_RED = REGISTRY.register("laboratory_roman_1_red", LaboratoryRoman1RedBlock::new);
		LABORATORY_ROMAN_10_RED = REGISTRY.register("laboratory_roman_10_red", LaboratoryRoman10RedBlock::new);
		LABORATORY_ROMAN_5_RED = REGISTRY.register("laboratory_roman_5_red", LaboratoryRoman5RedBlock::new);
		LABORATORY_STRIPE_RED = REGISTRY.register("laboratory_stripe_red", LaboratoryStripeRedBlock::new);
		LABORATORY_LEFT_ARROW_LIME = REGISTRY.register("laboratory_left_arrow_lime", LaboratoryLeftArrowLimeBlock::new);
		LABORATORY_RIGHT_ARROW_LIME = REGISTRY.register("laboratory_right_arrow_lime", LaboratoryRightArrowLimeBlock::new);
		LABORATORY_ROMAN_10_LIME = REGISTRY.register("laboratory_roman_10_lime", LaboratoryRoman10LimeBlock::new);
		LABORATORY_ROMAN_1_LIME = REGISTRY.register("laboratory_roman_1_lime", LaboratoryRoman1LimeBlock::new);
		LABORATORY_ROMAN_5_LIME = REGISTRY.register("laboratory_roman_5_lime", LaboratoryRoman5LimeBlock::new);
		LABORATORY_STRIPE_LIME = REGISTRY.register("laboratory_stripe_lime", LaboratoryStripeLimeBlock::new);
		RGB_BUFFER = REGISTRY.register("rgb_buffer", RGBBufferBlock::new);
		COW_CATCHER_RGB = REGISTRY.register("cow_catcher_rgb", CowCatcherRGBBlock::new);
		ANIMATED_SERVER_RACK = REGISTRY.register("animated_server_rack", AnimatedServerRackBlock::new);
		WHITE_FUNNEL = REGISTRY.register("white_funnel", WhiteFunnelBlock::new);
		LIGHT_GRAY_FUNNEL = REGISTRY.register("light_gray_funnel", LightGrayFunnelBlock::new);
		GRAY_FUNNEL = REGISTRY.register("gray_funnel", GrayFunnelBlock::new);
		BLACK_FUNNEL = REGISTRY.register("black_funnel", BlackFunnelBlock::new);
		BROWN_FUNNEL = REGISTRY.register("brown_funnel", BrownFunnelBlock::new);
		RED_FUNNEL = REGISTRY.register("red_funnel", RedFunnelBlock::new);
		ORANGE_FUNNEL = REGISTRY.register("orange_funnel", OrangeFunnelBlock::new);
		YELLOW_FUNNEL = REGISTRY.register("yellow_funnel", YellowFunnelBlock::new);
		LIME_FUNNEL = REGISTRY.register("lime_funnel", LimeFunnelBlock::new);
		GREEN_FUNNEL = REGISTRY.register("green_funnel", GreenFunnelBlock::new);
		CYAN_FUNNEL = REGISTRY.register("cyan_funnel", CyanFunnelBlock::new);
		LIGHT_BLUE_FUNNEL = REGISTRY.register("light_blue_funnel", LightBlueFunnelBlock::new);
		BLUE_FUNNEL = REGISTRY.register("blue_funnel", BlueFunnelBlock::new);
		PURPLE_FUNNEL = REGISTRY.register("purple_funnel", PurpleFunnelBlock::new);
		MAGENTA_FUNNEL = REGISTRY.register("magenta_funnel", MagentaFunnelBlock::new);
		PINK_FUNNEL = REGISTRY.register("pink_funnel", PinkFunnelBlock::new);
		RGB_FUNNEL = REGISTRY.register("rgb_funnel", RGBFunnelBlock::new);
		SMOKE_STACK_OPENING = REGISTRY.register("smoke_stack_opening", SmokeStackOpeningBlock::new);
	}
	// Start of user code block custom blocks
	// End of user code block custom blocks
}